-- Non-spatial subset of app/supabase/schema.sql, reused without rewriting it.
-- IF NOT EXISTS preserves an existing Supabase installation. PostGIS is not needed by this slice.
DO $$ BEGIN CREATE TYPE public.membership_role AS ENUM ('control_admin','prime_admin','site_manager','dispatcher','driver','receiver','viewer'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS public.organizations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,customer_code text NOT NULL UNIQUE,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.profiles(id uuid PRIMARY KEY REFERENCES auth.users(id),display_name text NOT NULL,phone text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.memberships(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id),user_id uuid NOT NULL REFERENCES auth.users(id),role public.membership_role NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,user_id));
CREATE TABLE IF NOT EXISTS public.projects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id),name text NOT NULL,status text NOT NULL DEFAULT 'active',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.sites(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id),project_id uuid NOT NULL REFERENCES public.projects(id),external_code text NOT NULL,name text NOT NULL,address text NOT NULL,start_on date,end_on date,status text NOT NULL DEFAULT 'active',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,external_code));
CREATE TABLE IF NOT EXISTS public.vehicles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id),registration_number text NOT NULL,display_name text NOT NULL,vehicle_class text NOT NULL,width_m numeric(4,2),height_m numeric(4,2),length_m numeric(5,2),gross_weight_t numeric(6,2),axle_weight_t numeric(5,1),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,registration_number));
CREATE TABLE IF NOT EXISTS public.drivers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id),profile_id uuid REFERENCES public.profiles(id),display_name text NOT NULL,license_expires_on date,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
