import {useEffect,useState} from 'react';
import {Building2,MapPin,RefreshCw} from 'lucide-react';
import {call} from '../integration/api';

export default function ConstructionSitesConnected({session,onOpen}){
 const [ctx,setCtx]=useState(null),[selected,setSelected]=useState(null),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const pendingKey=`ecodump-site-operation:${session.userId}`;
 const [pending,setPending]=useState(()=>{try{return JSON.parse(localStorage.getItem(pendingKey)||'null');}catch{return null;}});
 async function refresh(){setBusy(true);setError('');try{const next=await call(session.token,'/context');setCtx(next);setSelected(id=>id&&next.sites.some(s=>s.id===id)?id:next.sites[0]?.id||null);}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{refresh();},[session.token]);
 async function execute(op){setBusy(true);setError('');setNotice('');let acknowledged=false;try{await call(session.token,'/actions/site_update',{method:'POST',body:op.body,key:op.key});acknowledged=true;await refresh();localStorage.removeItem(pendingKey);setPending(null);setEditing(false);setNotice('現場情報をDBへ保存し、再取得を確認しました。');}catch(e){if(acknowledged||[400,403,409,422].includes(e.status)){localStorage.removeItem(pendingKey);setPending(null);setError(e.message);if(e.status===409)await refresh();}else setError('保存結果を確認できません。自動再送せず、処理結果を照会してください。');}finally{setBusy(false);}}
 async function save(e){e.preventDefault();if(pending)return;const f=new FormData(e.currentTarget),op={key:crypto.randomUUID(),body:{siteId:selected,expectedVersion:Number(f.get('version')),name:f.get('name'),address:f.get('address'),entrance:f.get('entrance'),contact:f.get('contact'),phone:f.get('phone'),notes:f.get('notes'),reason:f.get('reason')}};localStorage.setItem(pendingKey,JSON.stringify(op));setPending(op);await execute(op);}
 async function lookup(){setBusy(true);try{const result=await call(session.token,`/operations/${pending.key}`);if(result.state==='applied'){await refresh();localStorage.removeItem(pendingKey);setPending(null);setEditing(false);setNotice('処理済みであることと再取得を確認しました。');}else setError('DBで未処理と確認しました。内容を確認してから明示的に再送してください。');}catch{setError('操作結果を照会できません。結果確認中のまま保持します。');}finally{setBusy(false);}}
 const site=ctx?.sites.find(s=>s.id===selected);
 if(!ctx)return <p role="status">{error||'担当現場を取得中…'}</p>;
 return <div className="connected-root business-connected light"><div className="connected-main"><div className="connected-proof">隔離PostgreSQL・実API接続 <small>本番ではありません</small></div>{error&&<p className="error-box" role="alert">{error}</p>}{notice&&<p className="connected-success" role="status">{notice}</p>}{pending&&<section className="connected-pending"><p>結果確認中の操作：{pending.key}</p><button disabled={busy} onClick={lookup}>処理結果を照会</button></section>}<div className="connected-heading"><div><div className="eyebrow">CONSTRUCTION SITES</div><h1>担当現場</h1><p>A/B工区を共通DBの担当範囲で分離して表示します。</p></div><button className="secondary" disabled={busy} onClick={refresh}><RefreshCw size={16}/>再取得</button></div><div className="connected-grid">{ctx.sites.map(s=><button key={s.id} className={`connected-card ${s.id===selected?'selected':''}`} onClick={()=>{setSelected(s.id);setEditing(false);}}><Building2/><strong>{s.name}</strong><small>{s.organization_name}</small><span>{s.address}</span></button>)}</div>{site&&<section className="connected-card"><h2><MapPin size={18}/>{site.name}</h2>{editing?<form className="connected-form" onSubmit={save}><input type="hidden" name="version" value={site.version}/><div className="connected-grid"><label>現場・工区名<input name="name" defaultValue={site.name} required maxLength={200}/></label><label>所在地<input name="address" defaultValue={site.address}/></label><label>入口<input name="entrance" defaultValue={site.entrance||''}/></label><label>担当者<input name="contact" defaultValue={site.contact||''}/></label><label>連絡先<input name="phone" defaultValue={site.phone||''}/></label></div><label>搬出条件・注意事項<textarea name="notes" defaultValue={site.notes||''}/></label><label>変更理由<input name="reason" required maxLength={2000}/></label><button className="primary" disabled={busy||!!pending}>保存して再取得</button><button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(false)}>戻る</button></form>:<><dl><dt>会社</dt><dd>{site.organization_name}</dd><dt>所在地</dt><dd>{site.address||'未登録'}</dd><dt>入口</dt><dd>{site.entrance||'未登録'}</dd><dt>担当者</dt><dd>{site.contact||'未登録'}</dd><dt>連絡先</dt><dd>{site.phone||'未登録'}</dd><dt>搬出条件・注意事項</dt><dd>{site.notes||'未登録'}</dd></dl><button className="primary" onClick={()=>onOpen?.(site.id)}>現場詳細を開く</button><button className="secondary" onClick={()=>setEditing(true)}>現場情報を編集</button></>}</section>}{!ctx.sites.length&&<p className="empty-state">担当現場がありません。権限外の現場は取得していません。</p>}</div></div>;
}
