import DriverIssueForm from '../driver/DriverIssueForm.jsx';
import DriverReportCorrection from '../driver/DriverReportCorrection.jsx';
import DriverInbox from '../driver/DriverInbox.jsx';
import {driverRowKey,driverPlannedAt,driverPlannedQuantity,driverDone,assignmentSnapshot,reviewAssignments} from '../driver/connectedModel.mjs';
import DriverLocation from '../driver/DriverLocation.jsx';
import DriverDocuments from '../driver/documents/DriverDocuments.jsx';
import DriverIdentity from '../driver/documents/DriverIdentity.jsx';
import ReceiptEvidence from '../receiving/ReceiptEvidence';
import PhoneStatus from '../driver/PhoneStatus.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {Truck,ClipboardList,History,Bell,UserRound,ArrowLeft,RefreshCw,MapPin,Paperclip,Check,ShieldCheck,Sun} from 'lucide-react';
import {call,names,next} from './api';
import {isConfirmedRejection} from './delivery.mjs';
import '../driver/driver.css';
import './connected.css';
const labels={construction:'施工側',receiving:'受入側',driver:'ドライバー'};
const requested=new URLSearchParams(location.search).get('role')||(new URLSearchParams(location.search).get('app')==='driver'?'driver':'construction');
const initial=labels[requested]?requested:'construction';
const sessionKey=`ecodump-direct-session:${initial}`;
const dateToday=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());
const when=t=>new Date(t).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
const unit=u=>u==='m3'?'m³':u;
const rowKey=b=>b?.trip?.id||b?.id;
const bookingStatus={requested:'申請中',confirmed:'承認済み',change_requested:'変更承認待ち',rejected:'受入不可',cancelled:'取消',partially_completed:'一部完了・残便取消'};
function Confirm({data,close,accept,busy}){const ref=useRef(null);useEffect(()=>{const old=document.activeElement;ref.current.showModal();return()=>old?.focus();},[]);return <dialog ref={ref} className="driver-dialog" aria-labelledby="confirm-title" onCancel={e=>{e.preventDefault();if(!busy)close();}}><h2 id="confirm-title">{data.title}</h2><p>{data.message}</p><p>隔離検証DBへ保存します。本番データは使用しません。</p><button className="primary" disabled={busy} onClick={accept}>{busy?'通信中…':'内容を確認して保存'}</button><button className="secondary" disabled={busy} onClick={close}>戻る</button></dialog>}
export default function ConnectedApp({embedded=false,account=null,role:businessRole,view="home",bookingId=null,theme="light"}={}){
 const initial=businessRole||(labels[requested]?requested:'construction');
 const sessionKey=`ecodump-direct-session:${initial}`;
 const [session,setSession]=useState(()=>{try{return account||JSON.parse(sessionStorage.getItem(sessionKey)||'null');}catch{return null;}});
 const [ctx,setCtx]=useState(null),[rows,setRows]=useState([]),[role,setRole]=useState(initial),[tab,setTab]=useState(view),[selected,setSelected]=useState(bookingId),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[status,setStatus]=useState(''),[pending,setPending]=useState(null),[confirm,setConfirm]=useState(null),[creating,setCreating]=useState(false),[refreshed,setRefreshed]=useState(''),[date,setDate]=useState(()=>{const d=new URLSearchParams(location.search).get('date');return /^\d{4}-\d{2}-\d{2}$/.test(d||'')?d:dateToday();}),[dark,setDark]=useState(initial!=='driver'),[writing,setWriting]=useState(false);
 const lock=useRef(false),content=useRef(null),sessionToken=useRef(session?.token),requestId=useRef(0);sessionToken.current=session?.token;
 const [assignmentAlerts,setAssignmentAlerts]=useState({}),[online,setOnline]=useState(navigator.onLine);
 const previousAssignments=useRef({});
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 const [destination,setDestination]=useState('');
 const pendingKey=session?`ecodump-direct-operation:${session.userId}`:null;
 async function refresh(token=session?.token){const request=++requestId.current;setLoading(true);try{const [c,r,identity]=await Promise.all([call(token,'/context'),call(token,'/bookings'),call(token,'/driver-identity')]);if(sessionToken.current!==token||request!==requestId.current)return [];const records=r.bookings.flatMap(b=>b.trips?.length?b.trips.map(t=>({...b,...(t.trip?t:{}),trip:t.trip||t})):b);const fresh=records.map(b=>b.trip?{...b,trip:{...b.trip,vehiclePlate:b.trip.vehiclePlate||b.vehiclePlate||identity.vehicles.find(v=>v.id===b.trip.vehicleId)?.plate||b.trip.vehicle}}:b);const review=reviewAssignments(previousAssignments.current,fresh);previousAssignments.current=review.snapshots;setAssignmentAlerts(review.alerts);try{localStorage.setItem(`ecodump-driver-assignments:${session.userId}`,JSON.stringify(previousAssignments.current));}catch{}if(selected&&!fresh.some(b=>role==='driver'?driverRowKey(b)===selected:rowKey(b)===selected||b.id===selected)){setSelected(null);setConfirm(null);setNotice('対象便が現在の担当範囲から外れました。旧割当では送信できません。');}setCtx({...c,driverIdentity:identity});setRows(fresh);setRefreshed(new Date().toLocaleTimeString('ja-JP'));if(c.roles.length&&!c.roles.includes(role))setRole(c.roles[0]);return fresh;}catch(e){if(e.status===401&&sessionToken.current===token){sessionToken.current=null;setSession(null);setCtx(null);setRows([]);setSelected(null);setConfirm(null);sessionStorage.removeItem(sessionKey);}throw e;}finally{if(request===requestId.current)setLoading(false);}}
 useEffect(()=>{if(!embedded)document.title='ECO DUMP | 共通API・隔離DB検証';if(session){try{previousAssignments.current=JSON.parse(localStorage.getItem(`ecodump-driver-assignments:${session.userId}`)||sessionStorage.getItem(`ecodump-driver-assignments:${session.userId}`)||'{}');const p=JSON.parse(localStorage.getItem(pendingKey)||'null');setPending(p);if(p)setStatus('unknown');}catch{setError('未処理操作の読込に失敗しました。');}refresh().catch(e=>{setError(e.message);if(e.status===401){setSession(null);setCtx(null);setRows([]);setSelected(null);sessionStorage.removeItem(sessionKey);}});}},[session?.token]);
 useEffect(()=>{content.current?.scrollTo(0,0);},[tab,selected]);
 async function login(e){e.preventDefault();const f=new FormData(e.currentTarget);setError('');setLoading(true);try{const s=await call(null,'/session',{method:'POST',body:{email:f.get('email'),password:f.get('password')}});sessionStorage.setItem(sessionKey,JSON.stringify(s));previousAssignments.current={};setAssignmentAlerts({});setSession(s);}catch(e){setError(e.message);}finally{setLoading(false);}}
 async function logout(){if(pending){setError('処理結果を照会してからログアウトしてください。');return;}try{await call(session.token,'/session',{method:'DELETE'});sessionStorage.removeItem(sessionKey);sessionToken.current=null;requestId.current++;setSession(null);setCtx(null);setRows([]);previousAssignments.current={};setAssignmentAlerts({});setSelected(null);setCreating(false);setConfirm(null);setTab('home');setNotice('');setStatus('');}catch(e){setError(e.message);}}
 async function execute(op){if(lock.current)return;lock.current=true;setWriting(true);setStatus('sending');setError('');setNotice('');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);let acknowledged=false;try{const saved=await call(session.token,`/actions/${op.action}`,{method:'POST',body:op.body,key:op.key,signal:controller.signal});acknowledged=true;const fresh=await refresh();if(!fresh.some(b=>b.id===saved.bookingId))throw new Error('保存後の対象を再取得できません。');localStorage.removeItem(pendingKey);setPending(null);setStatus('sent');setNotice('DB保存と再取得を確認しました。');setCreating(false);}catch(e){if(!acknowledged&&isConfirmedRejection(e.status)){localStorage.removeItem(pendingKey);setPending(null);setStatus('failed');setError(e.message);if(e.status===409)await refresh().catch(()=>{});}else{setStatus('unknown');setError('保存結果を確認できません。再送せず「処理結果を照会」を押してください。');}}finally{clearTimeout(timer);setConfirm(null);lock.current=false;setWriting(false);}}
 async function mutate(action,body){if(lock.current||pending)return;const op={key:crypto.randomUUID(),action,body,userId:session.userId};try{localStorage.setItem(pendingKey,JSON.stringify(op));}catch{setError('操作IDを保持できないため送信していません。');return;}setPending(op);await execute(op);}
 async function lookup(){if(!pending||lock.current)return;setWriting(true);try{const r=await call(session.token,`/operations/${pending.key}`);if(r.state==='applied'){await refresh();localStorage.removeItem(pendingKey);setPending(null);setStatus('sent');setError('');setNotice('処理済みであることと再取得を確認しました。');setCreating(false);}else{setStatus('not_applied');setError('DBで未処理と確認しました。同じ操作IDで明示的に再送できます。');}}catch{setError('照会できません。結果確認中のまま保持しています。');}finally{setWriting(false);}}
 const ask=(title,message,action,body)=>setConfirm({title,message,action,body});
 const changeTab=t=>{setTab(t);setSelected(null);setCreating(false);setNotice('');if(!pending){setStatus('');setError('');}};
 const driver=role==='driver';
 const list=rows.filter(b=>driver?b.canReport:role==='construction'?b.canAssign:b.canConfirm);
 const visible=list.filter(b=>b.date===date&&(tab==='results'?(driver?driverDone(b):b.actual):true)).sort((a,b)=>(driver&&tab==='home'?Number(driverDone(a))-Number(driverDone(b)):0)||new Date(driverPlannedAt(a))-new Date(driverPlannedAt(b)));
 const current=list.find(b=>driver?driverRowKey(b)===selected:rowKey(b)===selected||b.id===selected);
 const assignmentBlocked=driver&&!!current&&!!assignmentAlerts[driverRowKey(current)];
 const menus=driver?[['home',Truck,'今日の運行'],['results',History,'運行履歴'],['notifications',Bell,'お知らせ'],['profile',UserRound,'マイページ']]:[['home',ClipboardList,role==='construction'?'搬出予定・直接予約':'搬入予約・受付'],['results',History,role==='construction'?'搬出実績':'受入実績'],['profile',UserRound,'担当範囲・接続情報']];
 const disabled=writing||!!pending||assignmentBlocked;
 async function download(a){try{const r=await fetch(`/api/direct/attachments/${a.id}`,{headers:{Authorization:`Bearer ${session.token}`}});if(!r.ok)throw Error('添付書類を取得できません。');const url=URL.createObjectURL(await r.blob());const link=document.createElement('a');link.href=url;link.download=a.filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e.message);}}
 async function upload(e,b){const f=e.target.files[0];e.target.value='';if(!f)return;if(f.size>2097152){setError('添付書類は2MB以下にしてください。');return;}const r=new FileReader();r.onerror=()=>setError('ファイルを読み込めません。');r.onload=()=>mutate('attachment',{bookingId:b.id,tripId:b.trip?.id,expectedTripVersion:b.trip?.version,filename:f.name,mime:f.type,base64:r.result.split(',')[1]});r.readAsDataURL(f);}
 function NewReservation(){const selectedDestination=destination||ctx.locations[0]?.id||'';const target=ctx.locations.find(l=>l.id===selectedDestination);return <form className="connected-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);ask('直接予約を申請','受入側へ申請中として表示します。受入側の確認後に予約が確定します。','create',{id:crypto.randomUUID(),siteId:f.get('site'),locationId:selectedDestination,quantity:Number(f.get('quantity')),unit:target.unit,soil:target.soil,plannedAt:new Date(`${f.get('date')}T${f.get('time')}:00+09:00`).toISOString(),agreementNote:f.get('note')});}}><h2>搬出予定・搬入予約を作成</h2><p>既存取引先への直接予約です。発生土マッチは経由しません。</p><div className="connected-grid"><label>搬出現場<select name="site" required>{ctx.sites.filter(s=>ctx.scopes.some(sc=>sc.site_id===s.id&&sc.role==='construction')).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>受入先<select value={selectedDestination} onChange={e=>setDestination(e.target.value)} required>{ctx.locations.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>搬入日（日本時間）<input type="date" name="date" defaultValue={date} required/></label><label>指定時刻<input type="time" name="time" defaultValue="09:00" required/></label><label>予定数量（{unit(target?.unit)}）<input name="quantity" type="number" min="0.001" step="0.001" defaultValue="7" required/></label><label>土質・受入条件<input value={target?.soil||''} readOnly/></label></div><label>直接取引の条件・合意内容（受入側確認前）<textarea aria-label="直接取引の条件・合意内容（受入側確認前）" name="note" required maxLength={2000} defaultValue="指定の土質・数量・日時で搬入を希望します。受入側で条件を確認してください。"/></label><button className="primary" disabled={disabled||!target}>予約を申請</button><button type="button" className="secondary" onClick={()=>setCreating(false)}>戻る</button></form>}
 function Detail({b}){return <><button className="back-button" onClick={()=>setSelected(null)}><ArrowLeft size={18}/>一覧へ戻る</button><h1>{driver?'運行詳細':'直接予約の詳細'}</h1><p className="connected-id">予約 {b.id}{b.trip&&<><br/>便 {b.trip.id} / {b.trip.rotation}往復目</>}</p><div className="connected-states"><span>条件合意：{b.agreementState==='agreed'?'合意済み':'確認待ち'}</span><span>予約：{b.status==='confirmed'?'確定':'申請中'}</span><span>運行：{b.trip?names[b.trip.status]:'未配車'}</span><span>受入実績：{b.actual?'確定':'未確定'}</span></div> {driver&&b.trip&&<section className="connected-card"><h2>状態報告</h2>{assignmentBlocked&&<p className="document-warning">配車内容が変わっています。下の変更内容を確認してから報告してください。</p>}<ol className="stage-list">{Object.entries(names).filter(([s])=>['site_arrived','in_transit','receiver_arrived','unloaded'].includes(s)).map(([s,label])=><li key={s} className={b.events.some(e=>e.state===s)?'done':''}><span>{b.events.some(e=>e.state===s)?<Check size={14}/>:'·'}</span>{label}</li>)}</ol><p>停車中に操作してください。到着報告は入場記録、荷下ろし完了は退場記録ではありません。受入実績は受入担当が別途確認・確定します。</p>{b.status!=='confirmed'?<p className="document-warning">予約が未確定または変更確認中のため、次の報告は停止しています。</p>:next[b.trip.status]?<button className="primary" disabled={disabled} onClick={()=>ask('運行状態を報告',`${names[next[b.trip.status]]}を実際に完了したことを確認してください。`,'report',{bookingId:b.id,tripId:b.trip.id,expectedVersion:b.trip.version,state:next[b.trip.status],reportedAt:new Date().toISOString()})}>{names[next[b.trip.status]]}を報告</button>:<p className="connected-success">{b.trip.status==='unloaded'?'荷下ろし完了をDBで確認済み':`この便は${names[b.trip.status]||b.trip.status}です。`}</p>}<a className="driver-document-jump" href="#driver-issue">問題報告・担当の確認依頼へ</a><details><summary>登録経路・位置情報</summary><p>登録された業務経路：未接続。ナビゲーション案内：未接続。登録経路とナビの案内は別です。</p><p>GPSの取得状態は下の「位置情報」で確認できます。共有・追跡・到着見込み計算は未接続です。</p></details></section>}
{driver&&assignmentAlerts[driverRowKey(b)]&&<section className="document-warning"><h2>配車内容が変更されました</h2>{assignmentAlerts[driverRowKey(b)].map(c=><p key={c.label}>{c.label}：{c.before||'未設定'} → {c.after||'未設定'}</p>)}<button disabled={writing||!!pending} onClick={()=>{const next={...previousAssignments.current,[driverRowKey(b)]:assignmentSnapshot(b)};try{localStorage.setItem(`ecodump-driver-assignments:${session.userId}`,JSON.stringify(next));}catch{setError('配車確認を端末に保持できません。確認を完了せず、報告を停止しています。');return;}previousAssignments.current=next;setAssignmentAlerts(a=>{const copy={...a};delete copy[driverRowKey(b)];return copy;});}}>変更内容を確認しました</button><p>確認するまで報告・伝票提出を停止します。</p></section>}{driver&&<a className="driver-document-jump" href="#driver-receipt">伝票を撮影・提出へ</a>}<section className="connected-card"><h2>運搬内容</h2><dl><dt>指定時刻</dt><dd>{when(driver?driverPlannedAt(b):b.plannedAt)}</dd><dt>土質・便の予定数量</dt><dd>{b.soil} / {driverPlannedQuantity(b)} {unit(b.unit)}</dd><dt>車両</dt><dd>{b.trip?.vehicle||'未割当'} / {b.trip?.vehiclePlate||b.vehiclePlate||'車番未登録'}</dd><dt>ドライバー</dt><dd>{b.trip?.driver||'未割当'}</dd></dl>{b.agreementNote&&<p>条件：{b.agreementNote}</p>}</section><div className="connected-grid">{[['搬出現場',b.site],['受入先',b.location]].map(([title,s])=><section key={title} className="connected-card"><h2><MapPin size={18}/>{title}</h2><h3>{s.name}</h3><p>{s.address}</p><dl><dt>入口</dt><dd>{s.entrance}</dd><dt>担当者</dt><dd>{s.contact}</dd><dt>連絡先</dt><dd>{s.phone||'検証データには電話番号未設定'}</dd></dl><p>{s.notes}</p></section>)}</div>
 {b.canConfirm&&b.status==='requested'&&<section className="connected-card"><h2>受入条件と予約を確認</h2><p>条件・数量・日時を確認します。受入容量はDBで検査します。</p><button className="primary" disabled={disabled} onClick={()=>ask('受入予約を確定',`${b.quantity} ${unit(b.unit)}の提示条件への合意を含め、予約を確定します。`,'confirm',{bookingId:b.id,expectedVersion:b.version,agree:true})}>条件を確認して予約確定</button></section>}
 {b.canAssign&&b.status==='confirmed'&&<form className="connected-card connected-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),hasTrip=list.some(x=>x.id===b.id&&x.trip);ask(hasTrip?'追加便を配車':'車両・ドライバーを割当',hasTrip?'既存便を変更せず、同じ予約へ追加便を作成します。':'この予約に1便を作成し、担当ドライバーへ表示します。',hasTrip?'trip_add':'assign',{bookingId:b.id,expectedVersion:b.version,vehicleId:f.get('vehicle'),driverId:f.get('driver'),...(hasTrip?{plannedAt:new Date(`${f.get('date')}T${f.get('time')}:00+09:00`).toISOString(),quantity:Number(f.get('quantity')),reason:f.get('reason')}:{})});}}><h2>{list.some(x=>x.id===b.id&&x.trip)?'追加便を配車':'車両・ドライバーの割当'}</h2><div className="connected-grid"><label>車両<select name="vehicle" required>{ctx.vehicles.map(v=><option key={v.id} value={v.id}>{v.display_name}（{v.external?`委託・${v.organization_name}`:'自社'}）</option>)}</select></label><label>ドライバー<select name="driver" required>{ctx.drivers.map(v=><option key={v.id} value={v.id}>{v.display_name}（{v.external?`委託・${v.organization_name}`:'自社'}）</option>)}</select></label>{list.some(x=>x.id===b.id&&x.trip)&&<><label>運行日<input name="date" type="date" defaultValue={b.date} required/></label><label>予定時刻<input name="time" type="time" defaultValue="11:00" required/></label><label>便予定数量（{unit(b.unit)}）<input name="quantity" type="number" min="0.001" step="0.001" required/></label><label>追加理由<input name="reason" required maxLength={2000}/></label></>}</div><button className="primary" disabled={disabled}>{list.some(x=>x.id===b.id&&x.trip)?'追加便を保存':'この内容で配車'}</button></form>}
 {!driver&&b.canAssign&&b.trip?.status==='assigned'&&<details className="connected-card"><summary>代車・代走・便取消</summary><form className="connected-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);ask('配車を変更','変更前の担当と理由を履歴に残し、旧担当からの送信を停止します。','trip_reassign',{bookingId:b.id,tripId:b.trip.id,expectedVersion:b.trip.version,vehicleId:f.get('vehicle'),driverId:f.get('driver'),reason:f.get('reason')});}}><div className="connected-grid"><label>変更後の車両<select name="vehicle" required>{ctx.vehicles.map(v=><option key={v.id} value={v.id}>{v.display_name}</option>)}</select></label><label>変更後のドライバー<select name="driver" required>{ctx.drivers.map(v=><option key={v.id} value={v.id}>{v.display_name}</option>)}</select></label></div><label>変更理由<input name="reason" required maxLength={2000}/></label><button className="secondary" disabled={disabled}>代車・代走を保存</button></form><form className="connected-form" onSubmit={e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');ask('この便を取消','他の便と既存実績は残します。','trip_cancel',{bookingId:b.id,tripId:b.trip.id,expectedVersion:b.trip.version,reason});}}><label>便取消理由<input name="reason" required maxLength={2000}/></label><button className="secondary" disabled={disabled}>この便だけ取消</button></form></details>}
 {!driver&&b.canAssign&&!['cancelled','rejected','partially_completed'].includes(b.status)&&<details className="connected-card"><summary>予約全体を取消</summary><form className="connected-form" onSubmit={e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');ask('予約を取消','未開始便を取消します。一部搬入済みの実績は削除しません。','booking_cancel',{bookingId:b.id,expectedVersion:b.version,reason});}}><label>取消理由<input name="reason" required maxLength={2000}/></label><button className="secondary" disabled={disabled}>予約を取消</button></form></details>}
 {b.canConfirm&&b.trip?.status==='unloaded'&&!b.actual&&!b.receiptRecord&&!b.receiptRecord&&<form className="connected-card connected-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);ask('受入実績を確定',`実績 ${f.get('actual')} ${unit(b.unit)} / 理由：${f.get('reason')||'差異なし'}。確定後の訂正機能は次工程です。`,'actual',{bookingId:b.id,tripId:b.trip.id,expectedVersion:b.trip.version,quantity:Number(f.get('actual')),unit:b.unit,differenceReason:f.get('reason')});}}><h2>実績数量の確認・確定</h2><label>受入実績数量（{unit(b.unit)}）<input name="actual" type="number" min="0.001" step="0.001" required defaultValue={b.quantity}/></label><label>差異理由（予定と異なる場合は必須）<textarea name="reason" maxLength={1000}/></label><button className="primary" disabled={disabled}>受入実績を確定</button></form>}
 {b.actual&&<section className="connected-card"><h2>受入実績：確定</h2><strong className="actual-quantity">{b.actual.quantity} {unit(b.actual.unit)}</strong><p>確定日時 {when(b.actual.confirmedAt)}</p><p>{b.actual.differenceReason||'差異なし'}</p></section>}
 {driver&&<><DriverLocation/><div id="driver-issue"><DriverIssueForm key={`${session.userId}:${b.trip.id}`} booking={b} session={session} ask={ask} disabled={disabled||driverDone(b)}/></div><DriverReportCorrection key={`correction:${b.trip.id}`} booking={b} ask={ask} disabled={disabled}/></>}
 {b.trip&&<DriverDocuments key={`${session.userId}:${b.trip.id}`} booking={b} session={session} driver={driver} refresh={refresh} disabled={disabled}/>}
 {!driver&&b.trip&&(b.canReport||b.canConfirm)&&<ReceiptEvidence booking={b} token={session.token} mutate={mutate} disabled={disabled} upload={upload}/>}<section className="connected-card"><h2><Paperclip size={18}/>添付書類</h2>{b.attachments.map(a=><button key={a.id} className="secondary" onClick={()=>download(a)}>{a.filename}を取得</button>)}{!b.attachments.length&&<p>添付書類はありません。</p>}{!b.actual&&<label className="connected-file">PNG・JPEG・PDFを追加（2MB以下）<input aria-label="添付書類を追加" type="file" accept="image/png,image/jpeg,application/pdf" disabled={disabled} onChange={e=>upload(e,b)}/></label>}<small>取引当事者と担当ドライバーのみ取得できます。</small></section><section className="connected-card"><h2>サーバー受領済みの報告履歴</h2>{b.events.map(e=><p key={e.id}>{names[e.state]}<br/>報告日時 {when(e.reportedAt)}<br/>サーバー受信 {when(e.receivedAt)} <span className="driver-chip">送信済み</span></p>)}{!b.events.length&&<p>報告はありません。</p>}</section></>}
 const main=<>{!online&&<p role="status" className="document-warning">通信切断を検知しました。下書きは端末に保持し、更新を自動再送しません。</p>}<div className="connected-proof"><ShieldCheck size={16}/>{driver?'検証用DBに接続':'隔離PostgreSQL・実API接続'} <small>本番ではありません</small></div>{error&&<p className="error-box" role="alert">{error}</p>}{notice&&<p className="connected-success" role="status">{notice}</p>}{status&&<p className="connected-delivery" role="status">{({sending:'通信中',sent:'送信済み・DB再取得確認済み',failed:'送信失敗（保存拒否）',unknown:'結果確認中',not_applied:'未送信・DB未処理確認済み'})[status]}</p>}{pending&&<div className="connected-pending"><p>操作ID：{pending.key}<br/>結果不明の更新は自動再送しません。</p><button disabled={writing} onClick={lookup}>処理結果を照会</button>{status==='not_applied'&&<button disabled={writing} onClick={()=>execute(pending)}>同じ操作IDで再送</button>}</div>}{loading&&!ctx&&<p role="status">担当情報を取得中…</p>}{ctx&&<><div className="connected-toolbar"><span>{ctx.profile.display_name}<small>最終取得 {refreshed}</small></span><button className="secondary" disabled={loading||writing} onClick={()=>refresh().then(()=>setError('')).catch(e=>setError(e.message))}><RefreshCw size={16}/>{loading?'取得中':'再取得'}</button></div>{current?Detail({b:current}):creating?NewReservation():tab==='profile'?<><h1>{driver?'マイページ':'担当範囲・接続情報'}</h1>{driver&&<DriverIdentity session={session} ctx={ctx} bookings={list.filter(b=>b.date===date)}/>}<section className="connected-card"><h2>{ctx.profile.display_name}</h2><p>役割：{ctx.roles.map(r=>labels[r]).join('・')||'権限なし'}</p><p>担当：{driver?'自分に割り当てられた便のみ':ctx.sites.map(s=>s.name).join('、')||'なし'}</p><p>保存先：接続先の隔離PostgreSQL</p><p>検証用アカウント認証。本番Supabase Authとは別です。</p><p>GPSは運行詳細で端末内確認のみ利用できます。管理側への位置共有とPush通知は未接続です。</p><button className="secondary" disabled={disabled} onClick={logout}>ログアウト</button></section></>:tab==='notifications'?<DriverInbox session={session} rows={list} open={setSelected} assignmentAlerts={assignmentAlerts}/>:<><div className="connected-heading"><div><div className="eyebrow">{labels[role]} · DIRECT TRANSPORT</div><h1>{tab==='results'?(driver?'運行履歴':role==='construction'?'搬出実績':'受入実績'):(driver?(date===dateToday()?'今日の運行':'指定日の運行'):role==='construction'?'搬出予定・直接予約':'搬入予約・受付')}</h1></div>{role==='construction'&&tab==='home'&&<button className="primary" disabled={disabled} onClick={()=>setCreating(true)}>搬出予定・予約を作成</button>}</div>{<label className="connected-date">表示日（日本時間）<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}
 {driver&&list.some(b=>b.site.name.includes('成田空港モデル'))&&<details className="driver-validation-note"><summary>成田モデル・架空データでの検証</summary><p>実際の空港工事・採石場の契約や受入条件ではありません。運搬方向：成田モデル現場 → 採石場。</p></details>}{driver&&tab==='home'&&<DriverIdentity session={session} ctx={ctx} bookings={visible}/>}
 {driver?<div>{visible.map((b,i)=><button key={driverRowKey(b)} className={`trip-card ${driverRowKey(b)===driverRowKey(visible.find(item=>!driverDone(item))||{})?'featured':''}`} onClick={()=>setSelected(driverRowKey(b))}><div className="trip-top"><span>{driverRowKey(b)===driverRowKey(visible.find(item=>!driverDone(item))||{})?'次の運行':'運行'} / {b.trip.rotation}往復目</span><span className="driver-chip">{names[b.trip.status]}</span></div><div className="trip-time">{when(driver?driverPlannedAt(b):b.plannedAt)}</div>{assignmentAlerts[driverRowKey(b)]&&<strong className="document-warning">配車変更・内容を確認してください</strong>}<div className="route-stops"><div><span className="point">A</span><strong>{b.site.name}</strong></div><div><span className="point destination">B</span><strong>{b.location.name}</strong></div></div><div className="trip-footer">{b.trip.vehicle} / {b.trip.vehiclePlate}<br/>便 {b.trip.id.slice(0,8)} · 予定 {driverPlannedQuantity(b)} {unit(b.trip.unit||b.unit)}</div><small>受入確定数量：{b.actual?`${b.actual.quantity} ${unit(b.actual.unit)}`:'未確定'} · DB取得済み</small><small>伝票：{({pending:'確認待ち',returned:'差戻し・再提出してください',confirmed:'確認済み'})[b.receiptRecord?.status]||'未提出'}</small></button>)}</div>:<div className="connected-table-wrap" tabIndex={0} role="region" aria-label="運搬一覧。横にスクロールして全項目を確認"><p className="connected-table-hint">複数便は便ごとに表示します。表は横にスクロールできます。</p><table><thead><tr><th>指定日時 / 予約・便</th><th>搬出現場 → 受入先</th><th>予約 / 便予定</th><th>予約</th><th>運行</th><th>受入実績</th><th>操作</th></tr></thead><tbody>{visible.map(b=><tr key={rowKey(b)}><td>{when(b.trip?.plannedAt||b.plannedAt)}<small>予約 {b.id.slice(0,8)}{b.trip&&` / 便 ${b.trip.id.slice(0,8)}`}</small></td><td>{b.site.name}<small>→ {b.location.name}</small></td><td>{b.quantity} {unit(b.unit)}{b.trip&&<small>便 {driverPlannedQuantity(b)} {unit(b.trip.unit||b.unit)}</small>}</td><td>{bookingStatus[b.status]||b.status}</td><td>{b.trip?`${names[b.trip.status]} / ${b.trip.rotation}便目`:'未配車'}</td><td>{b.actual?`${b.actual.quantity} ${unit(b.actual.unit)} 確定`:'未確定'}</td><td><button className="secondary" onClick={()=>setSelected(rowKey(b))}>詳細を確認</button></td></tr>)}</tbody></table></div>}{!visible.length&&<div className="empty-state"><Truck/><p>対象の記録はありません。</p><small>権限のある取引だけ表示しています。</small></div>}{tab==='results'&&<p className="muted">双方が同じDBの確定数量を参照します。運行完了と受入実績確定は別です。</p>}</>}</>}</>;
 if(embedded&&!session)return <p role="alert">セッションの有効期限が切れました。上部でログアウトしてから再度ログインしてください。</p>;
 if(!session)return <div className="connected-login"><form onSubmit={login}><img src={`${import.meta.env.BASE_URL}ecodump-logo.png`} alt="ECO DUMP"/><div className="eyebrow">ISOLATED VALIDATION</div><h1>{labels[initial]}ログイン</h1><p>共通API・DBの隔離検証環境です。</p><label>メールアドレス<input name="email" type="email" required autoComplete="username" defaultValue={`${initial==='receiving'?'receiver':initial}@sample.invalid`}/></label><label>検証用パスワード<input name="password" type="password" required autoComplete="current-password"/></label>{error&&<p role="alert" className="error-box">{error}</p>}<button className="primary" disabled={loading}>{loading?'認証中…':'ログイン'}</button><small>アカウント情報：app/server/.local/credentials.json<br/>本番の認証情報は使用しないでください。</small></form></div>;
 if(embedded)return <section className={`connected-root business-connected ${theme}`}><div className="connected-main" ref={content}>{main}</div>{confirm&&<Confirm data={confirm} close={()=>setConfirm(null)} busy={disabled} accept={()=>mutate(confirm.action,confirm.body)}/>}</section>;
 return <div className={`connected-root ${driver?'driver-preview':''} ${dark?'dark':'light'}`}>{driver?<><aside className="preview-caption"><img src={`${import.meta.env.BASE_URL}ecodump-logo.png`} alt="ECO DUMP"/><span>CONNECTED DRIVER</span><h1>運行報告を、<br/>同じデータへ。</h1><p>iPhone表示 · 共通API接続<br/>隔離PostgreSQLへ実保存</p></aside><section className="iphone-shell" aria-label="iPhone表示 API接続ドライバー"><div className="iphone-display"><PhoneStatus /><div className="driver-app"><header className="driver-header"><img src={`${import.meta.env.BASE_URL}ecodump-logo.png`} alt="ECO DUMP"/><div><b>ECO DUMP</b><small>ドライバー / DB接続検証</small></div><button className="icon-button" aria-label="明暗表示を切替" onClick={()=>setDark(v=>!v)}><Sun/></button></header><main className="driver-content" ref={content}>{main}</main><nav className="driver-bottom" aria-label="下部メニュー">{menus.map(([key,Icon,name])=><button key={key} className={tab===key?'active':''} onClick={()=>changeTab(key)}><Icon size={21}/><span>{name}</span></button>)}</nav></div><div className="iphone-home"><span/></div></div></section></>:<div className="connected-admin"><header className="connected-header"><img src={`${import.meta.env.BASE_URL}ecodump-logo.png`} alt="ECO DUMP"/><b>ECO DUMP</b><span>直接運搬 / 共通API検証</span><button onClick={()=>setDark(v=>!v)}>明暗表示</button><button disabled={disabled} onClick={logout}>ログアウト</button></header><aside className="connected-sidebar"><small>{labels[role]}業務</small>{menus.map(([key,Icon,name])=><button key={key} className={tab===key?'active':''} onClick={()=>changeTab(key)}><Icon size={19}/>{name}</button>)}<button onClick={()=>{sessionStorage.setItem(`ecodump:match:session:${role}`,JSON.stringify(session));location.href=`/?preview=app&role=${role}&page=matching`;}}>発生土マッチ（共通DB）</button><p>直接予約・マッチ合意からの予約を同じDBで確認します。</p><a href={`/?preview=app&role=${role}`}>既存の全機能試作を開く（別データ）</a></aside><main className="connected-main" ref={content}>{main}</main></div>}{confirm&&<Confirm data={confirm} close={()=>setConfirm(null)} busy={disabled} accept={()=>mutate(confirm.action,confirm.body)}/>}</div>;
}
