const database='ecodump-driver-documents-v1';
function open(){return new Promise((resolve,reject)=>{const r=indexedDB.open(database,1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function draftStore(key,value){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('drafts',value===undefined?'readonly':'readwrite');const s=tx.objectStore('drafts');const r=value===undefined?s.get(key):s.put(value,key);tx.oncomplete=()=>{db.close();resolve(r.result);};tx.onerror=()=>{db.close();reject(tx.error);};});}
// An OCR provider can later return candidates here. Manual confirmation remains required.
export const ocrCapability={connected:false,label:'自動読取は未接続です。原票を見て入力してください。'};
export function readPhoto(file){return new Promise((resolve,reject)=>{if(!['image/jpeg','image/png'].includes(file.type)||file.size>2097152)return reject(Error('JPEG・PNGの原本写真を2MB以下で選択してください。HEIC・大きい写真の自動変換は未接続です。'));const r=new FileReader();r.onload=()=>resolve({filename:file.name.slice(0,120),mime:file.type,base64:r.result.split(',')[1]});r.onerror=()=>reject(Error('写真を読み込めません。'));r.readAsDataURL(file);});}

// Only return summaries for the authenticated user. Original photos never enter the inbox.
export async function draftSummaries(userId){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('drafts','readonly');const request=tx.objectStore('drafts').openCursor();const result=[];request.onsuccess=()=>{const cursor=request.result;if(!cursor)return;const key=String(cursor.key);const value=cursor.value;if(key.startsWith(`${userId}:`)&&(value.photo||value.quantity||value.operation))result.push({tripId:key.slice(userId.length+1),state:value.operation?'unknown':value.state,operationKey:value.operation?.key,quantity:value.quantity,unit:value.unit});cursor.continue();};tx.oncomplete=()=>{db.close();resolve(result);};tx.onerror=()=>{db.close();reject(tx.error);};});}
