import React,{useEffect,useRef,useState} from 'react';
import {Camera,FileCheck,AlertCircle} from 'lucide-react';
import {call} from '../../integration/api';
import {isConfirmedRejection} from '../../integration/delivery.mjs';
import {draftStore,readPhoto,ocrCapability} from './draftStore.mjs';
import './documents.css';
const unit=u=>u==='m3'?'m³':u;
const labels={pending:'管理者の確認待ち',returned:'差戻し・修正が必要',confirmed:'受入側が実績確定済み'};
const stamp=t=>new Date(t).toLocaleString('ja-JP');
export default function DriverDocuments({booking:b,session,driver,refresh,disabled=false}){
 const key=`${session.userId}:${b.trip.id}`;
 const [draft,setDraft]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[documents,setDocuments]=useState([]),[photo,setPhoto]=useState(null),[review,setReview]=useState(false);
 const current=useRef(null),queue=useRef(Promise.resolve()),lock=useRef(false),loaded=useRef(false);
 const receipt=b.receiptRecord;
 const blank=()=>({fields:{date:b.date,number:'',missingNumberReason:'',item:b.soil,plate:b.trip.vehiclePlate||b.trip.vehicle,origin:b.site.name,destination:b.location.name,gross:'',tare:'',net:'',checked:false},quantity:'',unit:b.unit,reason:'',tripVersion:b.trip.version,state:'unsent',photo:null,operation:null});
 async function loadFields(){const r=await call(session.token,`/driver-document-fields?bookingId=${b.id}&tripId=${b.trip.id}`);setDocuments(r.documents);}
 useEffect(()=>{let active=true;loaded.current=false;loadFields().catch(e=>setError(e.message));if(driver)draftStore(key).then(d=>{if(!active)return;const v=d||blank();if(v.tripVersion===undefined)v.tripVersion=null;if(v.operation)v.state='unknown';else if(receipt?.status==='returned'&&v.state==='sent'){v.state='unsent';v.fields.checked=false;v.reason='';}current.current=v;setDraft(v);loaded.current=true;}).catch(()=>setError('端末保存を利用できません。送信せずブラウザの保存設定を確認してください。'));return()=>{active=false;};},[key,session.token]);
 useEffect(()=>{loadFields().catch(e=>setError(e.message));if(driver&&loaded.current&&receipt?.status==='returned'&&current.current?.state==='sent'){persist({...current.current,state:'unsent',reason:'',fields:{...current.current.fields,checked:false}}).catch(()=>setError('下書きを保存できません。'));setMessage('差戻し理由を確認し、修正して再提出してください。');}},[receipt?.version]);
 const persist=v=>{current.current=v;setDraft(v);queue.current=queue.current.catch(()=>{}).then(()=>draftStore(key,v));return queue.current;};
 function change(p){setReview(false);setMessage('');persist({...current.current,...p,state:'unsent'}).then(()=>setMessage('端末に下書き保存済み・未送信')).catch(()=>setError('端末保存に失敗しました。写真・入力を保存できていません。'));}
 async function choose(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;try{const p=await readPhoto(f);await persist({...current.current,photo:p,state:'unsent',fields:{...current.current.fields,checked:false}});setReview(false);setMessage('原本写真を端末に保存しました。まだ提出していません。');}catch(e){setError(e.message);}}
 async function saved(){await refresh();await loadFields();await persist({...current.current,operation:null,state:'sent'});setReview(false);setMessage('送信済み・DB保存後の再取得を確認しました。');}
 async function send(op){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');let acknowledged=false;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{await persist({...current.current,operation:op,state:'sending'});await call(session.token,'/driver-document-submit',{method:'POST',body:op.body,key:op.key,signal:controller.signal});acknowledged=true;await saved();}catch(e){if(!acknowledged&&isConfirmedRejection(e.status)){await persist({...current.current,operation:null,state:'failed'});setError(e.message);if(e.status===409)await refresh();}else{await persist({...current.current,operation:op,state:'unknown'});setError('結果を確認できません。再送せず処理結果を照会してください。');}}finally{clearTimeout(timer);lock.current=false;setBusy(false);}}
 async function submit(){if(lock.current||current.current.operation||!review)return;if(current.current.tripVersion!==b.trip.version){setError('運行情報が更新されています。最新の割当を再確認してください。');return;}try{await queue.current;const d=current.current;if(!d.photo||!d.fields.checked)throw Error('原票写真と入力内容を確認してください。');const op={key:crypto.randomUUID(),body:{bookingId:b.id,tripId:b.trip.id,expectedTripVersion:d.tripVersion,expectedVersion:receipt?.version||0,quantity:Number(d.quantity),unit:d.unit,reason:d.reason,fields:d.fields,...d.photo}};await send(op);}catch(e){setError(e.message);}}
 async function lookup(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const r=await call(session.token,`/operations/${current.current.operation.key}`);if(r.state==='applied')await saved();else{await persist({...current.current,state:'not_applied'});setMessage('DBに未処理であることを確認しました。同じ操作IDで再送できます。');}}catch(e){setError('照会できません。写真と操作IDは端末に保持しています。');}finally{lock.current=false;setBusy(false);}}
 async function viewPhoto(id){try{const r=await fetch(`/api/direct/attachments/${id}`,{headers:{Authorization:`Bearer ${session.token}`}});if(!r.ok)throw Error('原本写真を取得できません。');const blob=await r.blob();const reader=new FileReader();reader.onload=()=>setPhoto(reader.result);reader.readAsDataURL(blob);}catch(e){setError(e.message);}}
 const assignmentChanged=driver&&draft&&draft.tripVersion!==b.trip.version;
 const locked=busy||disabled||!!draft?.operation||assignmentChanged;
 const editable=driver&&!b.actual&&(!receipt||receipt.status==='returned');
 return <section id="driver-receipt" className="connected-card driver-documents" aria-label="運行の伝票"><h2><Camera size={20}/>伝票を撮影・提出</h2><p>対象便 {b.trip.id.slice(0,8)} / {b.trip.rotation}往復目<br/>{b.site.name} → {b.location.name}</p><p>この運行の原票写真と手入力を提出します。提出だけで数量・受入実績は確定しません。</p>
 {error&&<p role="alert" className="error-box">{error}</p>}{message&&<p role="status">{message}</p>}
 {receipt&&<div className={`document-status ${receipt.status}`}><strong>{labels[receipt.status]}</strong><p>{receipt.quantity} {unit(receipt.unit)} / 提出版 {receipt.version}</p>{receipt.reason&&<p>確認・差戻し理由：{receipt.reason}</p>}<button className="secondary" onClick={()=>viewPhoto(receipt.attachment_id)}>提出した原本写真を確認</button></div>}
 {photo&&<div><img className="receipt-photo" src={photo} alt="DBから取得した伝票原本"/><button onClick={()=>setPhoto(null)}>写真を閉じる</button></div>}
 {editable&&assignmentChanged&&!draft?.operation&&<div className="document-warning"><p>運行情報が更新されました。配車・車番・担当・行先を確認するまで提出できません。</p><p>{b.trip.vehiclePlate||b.trip.vehicle} / {b.trip.driver}<br/>{b.site.name} → {b.location.name}</p><button disabled={busy||disabled} onClick={()=>change({tripVersion:b.trip.version,fields:{...draft.fields,checked:false}})}>最新の割当を確認して入力を引き継ぐ</button></div>}
 {editable&&draft&&loaded.current&&<form className="connected-form" onSubmit={e=>{e.preventDefault();setReview(true);setError('');}}><fieldset disabled={locked}>
 <p className="document-delivery" role="status">{({unsent:'未送信・端末下書き',sending:'送信中',unknown:'結果確認中',not_applied:'未送信・DB未処理確認済み',sent:'送信済み',failed:'送信失敗・入力を保持'})[draft.state]}</p>
 <label className="photo-picker"><Camera/>伝票を撮影<input aria-label="伝票を撮影" type="file" accept="image/jpeg,image/png" capture="environment" onChange={choose}/></label>
 <label>保存済みの写真を選択<input aria-label="保存済みの伝票写真" type="file" accept="image/jpeg,image/png" onChange={choose}/></label><small>JPEG / PNG・2MB以下。選択した原本を変換せず保存します。</small>
 {draft.photo&&<img className="receipt-photo" alt="提出前の原本写真" src={`data:${draft.photo.mime};base64,${draft.photo.base64}`}/>}
 <p>{ocrCapability.label}</p>
 {[['date','伝票日付','date'],['number','伝票番号','text'],['missingNumberReason','番号がない場合の理由','text'],['item','品名・土質','text'],['plate','原票の車番','text'],['origin','原票の搬出元','text'],['destination','原票の受入先','text']].map(([name,label,type])=><label key={name}>{label}<input type={type} value={draft.fields[name]} maxLength={160} required={!['number','missingNumberReason'].includes(name)} onChange={e=>change({fields:{...draft.fields,[name]:e.target.value,checked:false}})}/></label>)}
 {draft.fields.plate!==(b.trip.vehiclePlate||b.trip.vehicle)&&<p className="document-warning">割当表示と原票の車番が異なります。原票を確認し、管理者へお知らせください。</p>}
 <div className="document-pair"><label>原票の数量<input inputMode="decimal" type="number" min="0.001" max="999999999.999" step="0.001" required value={draft.quantity} onChange={e=>change({quantity:e.target.value,fields:{...draft.fields,checked:false}})}/></label><label>原票の単位<select value={draft.unit} onChange={e=>change({unit:e.target.value,fields:{...draft.fields,checked:false}})}><option value="m3">m³</option><option value="t">t</option></select></label></div><small>t と m³ は換算しません。予定単位と異なる場合も原票のまま提出します。</small>
 <details><summary>計量票の追加項目（原票記載どおり・任意）</summary>{[['gross','総重量'],['tare','空車重量'],['net','正味重量']].map(([name,label])=><label key={name}>{label}（単位も記入）<input value={draft.fields[name]} maxLength={80} onChange={e=>change({fields:{...draft.fields,[name]:e.target.value,checked:false}})}/></label>)}<small>正味重量は自動計算しません。</small></details>
 <label>{receipt?'修正理由（必須）':'管理者へのメモ'}<textarea value={draft.reason} required={!!receipt} maxLength={1000} onChange={e=>change({reason:e.target.value})}/></label>
 <label className="document-check"><input type="checkbox" required checked={draft.fields.checked} onChange={e=>change({fields:{...draft.fields,checked:e.target.checked}})}/>写真・数量・単位・運行の対応を確認しました</label>
 <button className="primary" disabled={!draft.photo||(!draft.fields.number.trim()&&!draft.fields.missingNumberReason.trim())}>提出内容を確認</button></fieldset>
 {review&&!locked&&<div className="document-review"><h3><FileCheck size={19}/>提出前の確認</h3><p>{b.site.name} → {b.location.name}</p><strong>{draft.quantity} {unit(draft.unit)}</strong><p>原票番号：{draft.fields.number||`番号なし（${draft.fields.missingNumberReason}）`}</p><p>管理者の確認待ちとして保存します。</p><button type="button" className="primary" onClick={submit}>この内容で伝票を提出</button></div>}
 </form>}
 {draft?.operation&&<div className="document-warning"><p>結果不明の更新は自動再送しません。</p><button disabled={busy} onClick={lookup}>伝票の処理結果を照会</button>{draft.state==='not_applied'&&<button disabled={busy} onClick={()=>send(draft.operation)}>同じ操作IDで伝票を再送</button>}</div>}
 {driver&&!editable&&!receipt&&<p>受入実績確定後の追加提出は現在できません。管理者へ確認してください。</p>}
 <details><summary>提出・修正・確認の履歴</summary>{(b.receiptHistory||[]).map(h=><article key={h.id}><strong>{({receipt_submit:'提出',receipt_return:'差戻し',receipt_confirm:'受入実績確定',receipt_correct:'実績訂正'})[h.action]||h.action}</strong><p>{stamp(h.recorded_at)} / {h.actorName}</p><p>{h.before_data&&`${h.before_data.quantity} ${unit(h.before_data.unit)} → `}{h.after_data.quantity} {unit(h.after_data.unit)} {h.reason}</p><button onClick={()=>viewPhoto(h.after_data.attachment_id)}>この版の原本写真</button></article>)}{documents.map(d=><article key={d.attachment_id}><p>{stamp(d.submitted_at)} / {d.fields.number||'伝票番号なし'}</p><p>{d.fields.item} / 車番 {d.fields.plate}</p><p>{d.fields.origin} → {d.fields.destination}</p><p>総重量 {d.fields.gross||'記載なし'} / 空車 {d.fields.tare||'記載なし'} / 正味 {d.fields.net||'記載なし'}</p></article>)}{!b.receiptHistory?.length&&<p>提出履歴はありません。</p>}</details>
 </section>;
}
