import { test, expect } from '@playwright/test';
const entry='/?preview=app&role=construction&demo=1&navigationReview=1';
for (const theme of ['dark','light']) for (const width of [1024,768]) {
 test(`tablet search and receiving date controls are available on entry ${theme} ${width}`,async({page})=>{
  await page.setViewportSize({width,height:1000});
  await page.addInitScript(t=>localStorage.setItem('ecodump-theme',t),theme);
  await page.goto(`${entry}&page=users`);
  const search=page.locator('.search-panel');
  await expect(search.getByRole('textbox')).toBeInViewport();
  await expect(search.getByRole('button',{name:'検索',exact:true})).toBeInViewport();
  await search.getByRole('textbox').fill('該当するユーザーなし');
  await search.getByRole('button',{name:'検索',exact:true}).click();
  await expect(search).toContainText('検索結果：0件');
  await page.goto('/?preview=app&role=receiving&page=transport&demo=1');
  const toolbar=page.locator('.receiving-toolbar');
  await expect(toolbar.getByRole('button',{name:'翌日',exact:true})).toBeInViewport();
  await expect(page.getByRole('button',{name:'受入実績を見る',exact:true})).toBeInViewport();
  const date=toolbar.locator('input[type=date]');const initial=await date.inputValue();
  await toolbar.getByRole('button',{name:'翌日',exact:true}).click();
  await expect(date).not.toHaveValue(initial);
  await toolbar.getByRole('button',{name:'前日',exact:true}).click();
  await expect(date).toHaveValue(initial);
 });
}
test('global search opens the selected current master ID and project is an honest display example', async ({page}) => {
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(`${entry}&page=transport`);
  await expect(page.locator('.sidebar-suite-logo')).toHaveCount(0);
  await expect(page.locator('.sidebar-suite-nav button')).toHaveCount(3);
  await page.locator('.control-project').click();
  await expect(page.getByRole('menu')).toContainText('名称のみ切り替え');
  await page.getByRole('button',{name:/湾岸再開発プロジェクト/}).click();
  await expect(page.locator('.review-site-table tbody > tr:not(.review-site-expanded-row)')).toHaveCount(23);
  const search=page.getByRole('textbox',{name:'全体検索',exact:true});
  await search.fill('32184');
  await page.locator('.global-search-results button').click();
  await expect(page.locator('.review-site-inline-detail')).toContainText('32184');
  await search.fill('佐藤');
  await expect(page.locator('.global-search-results')).toContainText('ドライバー');
  await page.locator('.global-search-results button').click();
  await expect(page).toHaveURL(/page=drivers/);
  await expect(page.getByRole('dialog')).toContainText('佐藤 健');
  await page.keyboard.press('Escape');
  await search.fill('01-02');
  await page.locator('.global-search-results button').click();
  await expect(page).toHaveURL(/page=vehicles/);
  await expect(page.getByRole('dialog')).toContainText('成田 100 を 01-02');
});
test('page help differs from common help and compact demo detail remains available', async ({page}) => {
  await page.goto(`${entry}&page=labor`);
  await page.locator('.compact-demo-notice summary').click();
  await expect(page.locator('.compact-demo-notice details')).toHaveAttribute('open','');
  await page.locator('.page-header').getByRole('button',{name:'ヘルプ',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('書類カテゴリ');
  await page.keyboard.press('Escape');
  await page.locator('.control-topbar').getByRole('button',{name:'ヘルプ',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('上部ロゴ');
  await page.keyboard.press('Escape');
  await expect(page.locator('.sidebar-footer button')).toHaveCount(0);
});
test('operation rows are time ordered and return preserves selected trip and state filter',async({page})=>{
 await page.goto(`${entry}&page=control`);
 await page.getByRole('button',{name:'すべての便を表示',exact:true}).click();
 const times=await page.locator('.review-timeline time').allTextContents();
 expect(times).toEqual([...times].sort());
 await page.getByRole('button',{name:/遅延\s*1\s*便/}).click();
 await page.locator('.review-timeline > button').click();
 await expect(page.locator('.map-selection')).toContainText('TR-20260820-02');
 await page.getByRole('button',{name:'配車を組む',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'TR-20260820-02 配車操作',exact:true})).toBeVisible();
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'運行管制へ戻る',exact:true}).click();
 await expect(page.getByRole('combobox',{name:'運行の表示条件',exact:true})).toHaveValue('遅延');
 await expect(page.locator('.map-selection')).toContainText('TR-20260820-02');
});
test('document state shortcuts retain distinct records and categories',async({page})=>{
 await page.goto(`${entry}&page=labor`);
 await expect(page.locator('.review-document-row')).toHaveCount(18);
 await page.getByRole('button',{name:'不足・差戻し',exact:true}).click();
 await expect(page.locator('.review-document-company')).toHaveCount(1);
 await expect(page.locator('.review-document-company')).toHaveAttribute('data-company-id','NC-03');
 await page.getByRole('button',{name:'確認待ち',exact:true}).click();
 await expect(page.locator('.review-document-company')).toHaveAttribute('data-company-id','NC-02');
 await page.getByRole('combobox',{name:'表示する書類',exact:true}).selectOption('許可情報');
 await expect(page.locator('.review-document-row')).toHaveCount(1);
 await expect(page.locator('.review-document-row')).toContainText('建設業許可情報');
 await page.reload();
 await expect(page.getByRole('button',{name:'確認待ち',exact:true})).toHaveAttribute('aria-pressed','true');
});
test('matching filters apply to candidates, documents stay scoped, and input draft survives closing',async({page})=>{
 await page.goto(`${entry}&page=matching`);
 await page.getByRole('button',{name:'受入れから探す',exact:true}).click();
 await expect(page.locator('.match-card')).toHaveCount(3);
 await page.getByRole('button',{name:'詳細条件を開く',exact:true}).click();
 await page.getByLabel('最大距離（km）',{exact:true}).fill('20');
 await expect(page.locator('.match-card')).toHaveCount(1);
 await expect(page.locator('.match-detail')).toContainText('湾岸第2受入ヤード');
 await page.getByRole('button',{name:'必要書類を確認',exact:true}).click();
 await expect(page.getByRole('dialog')).toContainText('MT-2026-001');
 await expect(page.getByRole('dialog')).toContainText('未確認・実ファイル未接続');
 await page.getByRole('dialog').getByRole('button',{name:'確認する',exact:true}).first().click();
 await expect(page.getByRole('dialog').getByRole('status')).toContainText('土質試験結果');
 await page.keyboard.press('Escape');
 await page.getByLabel('最大距離（km）',{exact:true}).fill('1');
 await expect(page.locator('.match-card')).toHaveCount(0);
 await expect(page.locator('.match-detail')).toHaveCount(0);
 await page.getByRole('button',{name:'詳細条件をクリア',exact:true}).click();
 await page.getByRole('button',{name:'新しい案件を登録',exact:true}).click();
 await page.getByLabel('総土量（m³）',{exact:true}).fill('9876');
 await page.getByRole('button',{name:'閉じる（下書きを保持）',exact:true}).click();
 await page.getByRole('button',{name:'新しい案件を登録',exact:true}).click();
 await expect(page.getByLabel('総土量（m³）',{exact:true})).toHaveValue('9876');
 await page.getByRole('button',{name:'入力内容を確認（未保存）',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'入力内容の確認（未保存）',exact:true})).toContainText('9876 m³');
 await page.keyboard.press('Escape');
 await expect(page.getByLabel('総土量（m³）',{exact:true})).toHaveValue('9876');
});
test('capacity chart keeps vertical bars and day window with the same scoped breakdown',async({page})=>{
 await page.goto(`${entry}&page=matching`);
 await expect(page.locator('.match-connected-chart svg')).toHaveCount(0);
 await expect(page.locator('.match-chart-column')).toHaveCount(4);
 await expect(page.locator('.cap-a-columns button')).toHaveCount(12);
 await page.getByRole('combobox',{name:'容量グラフの期間',exact:true}).selectOption('2');
 await page.getByRole('combobox',{name:'日別グラフの表示範囲',exact:true}).selectOption('1');
 await expect(page.locator('.cap-a-columns button')).toHaveCount(7);
 await expect(page.locator('.cap-a-month')).toHaveText(['8日','9日','10日','11日','12日','13日','14日']);
 await page.locator('.cap-a-columns button').nth(2).click();
 await expect(page.locator('.cap-a-detail h4')).toHaveText('10日の内訳');
 await expect(page.locator('.cap-a-table')).toContainText('モデル現場A');
 await expect(page.locator('.cap-a')).toContainText('単位換算は行いません');
});

test('company editing draft survives a different module and reload',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto(`${entry}&page=company`);
 await page.locator('main .service-menu').getByRole('button',{name:'労務安全項目',exact:true}).click();
 await page.getByRole('button',{name:'編集',exact:true}).click();
 await page.getByLabel('代表者情報 代表者名',{exact:true}).fill('保持を確認する担当者');
 await page.locator('.sidebar').getByRole('button',{name:'運行管理',exact:true}).click();
 await page.locator('.sidebar').getByRole('button',{name:'基本台帳',exact:true}).click();
 await page.locator('main .service-menu').getByRole('button',{name:'労務安全項目',exact:true}).click();
 await expect(page.getByLabel('代表者情報 代表者名',{exact:true})).toHaveValue('保持を確認する担当者');
 await page.reload();await expect(page.getByLabel('代表者情報 代表者名',{exact:true})).toHaveValue('保持を確認する担当者');
});

test('receiving control counts remain scoped and clicking assigned filters the actual trips',async({page})=>{
 await page.goto('/?preview=app&role=receiving&page=control&demo=1');
 await expect(page.locator('.timeline-panel header dl')).toHaveCount(0);
 await page.getByRole('button',{name:/配車済み\s*4\s*便/}).click();
 await expect(page.locator('.timeline-list > button')).toHaveCount(4);
 await expect(page.locator('.control-summary')).toContainText('4');
 await page.getByRole('combobox',{name:'受入場所',exact:true}).selectOption('栃木モデル採石場〈架空〉');
 await expect(page.locator('.timeline-list > button')).toHaveCount(2);
 await expect(page.locator('.timeline-panel header')).toContainText('選択中：TR-20260820-01');
 await expect(page.locator('.timeline-list > button.selected')).toContainText('TR-20260820-01');
 await page.getByRole('button',{name:'地図と並べる',exact:true}).click();
 await expect(page.locator('.map-selection')).toContainText('TR-20260820-01');
 expect(await page.locator('.map-selection').evaluate(e=>getComputedStyle(e).position)).toBe('static');
 const map=page.getByRole('region',{name:'運行地図と選択便の詳細',exact:true});
 expect(await map.evaluate(e=>getComputedStyle(e).overflowY)).toBe('auto');
 await map.focus();await page.keyboard.press('End');
 await expect(page.locator('.map-updated')).toBeInViewport();
 await page.getByRole('combobox',{name:'状態',exact:true}).selectOption('遅延');
 await expect(page.locator('.timeline-list > button')).toHaveCount(0);
 await expect(page.locator('.timeline-panel header')).toContainText('対象便なし');
 await expect(page.locator('.timeline-detail-action')).toBeDisabled();
});

test('manual site selection replaces global search scope across results and browser back',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto(`${entry}&page=transport`);
 await page.getByRole('textbox',{name:'全体検索',exact:true}).fill('32184');
 await page.locator('.global-search-results button').click();
 await expect(page.locator('.review-site-inline-detail')).toContainText('32184');
 await page.getByRole('combobox',{name:'現場',exact:true}).selectOption('成田空港モデル現場 A工区');
 await page.getByRole('button',{name:'搬出実績を見る',exact:true}).click();
 await expect(page).toHaveURL(/page=results/);
 await page.goBack();
 await expect(page.getByRole('combobox',{name:'現場',exact:true})).toHaveValue('成田空港モデル現場 A工区');
 await expect(page.locator('.review-site-inline-detail')).toContainText('32182');
 await expect(page.locator('.review-site-inline-detail')).not.toContainText('32184');
});

test('mobile matching form is visible, traps keyboard focus and retains draft after confirmation',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto(`${entry}&page=matching`);
 const opener=page.getByRole('button',{name:'新しい案件を登録',exact:true});await opener.click();
 const form=page.getByRole('dialog',{name:'マッチング案件登録',exact:true});
 const heading=await form.locator('h2').boundingBox();expect(heading.y).toBeGreaterThanOrEqual(0);
 expect(heading.y+heading.height).toBeLessThanOrEqual(844);
 expect(await form.locator('h2').evaluate(e=>{const r=e.getBoundingClientRect();return [r.y+1,r.y+r.height/2,r.bottom-1].every(y=>e.contains(document.elementFromPoint(r.x+r.width/2,y)));})).toBe(true);
 await form.getByRole('combobox',{name:'案件区分',exact:true}).focus();await page.keyboard.press('Shift+Tab');
 await expect(form.getByRole('button',{name:'入力内容を確認（未保存）',exact:true})).toBeFocused();
 await page.keyboard.press('Tab');await expect(form.getByRole('combobox',{name:'案件区分',exact:true})).toBeFocused();
 await form.getByLabel('総土量（m³）',{exact:true}).fill('6543');
 await form.getByRole('button',{name:'入力内容を確認（未保存）',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'入力内容の確認（未保存）',exact:true})).toContainText('6543 m³');
 await page.keyboard.press('Escape');await expect(form.getByLabel('総土量（m³）',{exact:true})).toHaveValue('6543');
 await page.keyboard.press('Escape');await expect(form).toHaveCount(0);await expect(opener).toBeFocused();
});

test('unavailable draft storage preserves input and never reports that it was retained in storage',async({page})=>{
 await page.addInitScript(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='ecodump-matching-create-draft')throw new DOMException('Storage unavailable','QuotaExceededError');return original.call(this,key,value);};});
 await page.goto(`${entry}&page=matching`);await page.getByRole('button',{name:'新しい案件を登録',exact:true}).click();
 const form=page.getByRole('dialog',{name:'マッチング案件登録',exact:true});
 await form.getByLabel('総土量（m³）',{exact:true}).fill('4321');
 await expect(form.getByRole('alert')).toContainText('入力は画面内に残っています');
 await form.getByRole('button',{name:'入力内容を確認（未保存）',exact:true}).click();
 const confirmation=page.getByRole('dialog',{name:'入力内容の確認（未保存）',exact:true});
 await expect(confirmation).toContainText('4321 m³');await expect(confirmation).toContainText('保持できません');
 await expect(confirmation).not.toContainText('保持しました');await page.keyboard.press('Escape');
 await expect(form.getByLabel('総土量（m³）',{exact:true})).toHaveValue('4321');
});
