import {useEffect,useRef,useState} from 'react';
import ReceivingEvidence from './ReceivingEvidence';
import {filters,summarize,cancelled} from './receivingSummary.mjs';
export function QuantitySummary({rows,onSelect}){const s=summarize(rows);return <div className="receiving-quantity-summary"><p><button onClick={()=>onSelect('予定')}>車両実台数 {s.vehicles}台 / 延べ運行回数 {s.rotations}便</button></p>{s.quantities.map(q=><div key={q.unit}><b>{q.unit}</b><button onClick={()=>onSelect('予定',q.unit)}>予定 {q.planned.toFixed(3)}</button><button onClick={()=>onSelect('実績',q.unit)}>原票確認済み {q.confirmed.toFixed(3)}</button><button onClick={()=>onSelect('確認待ち数量',q.unit)}>確認待ち {q.pending.toFixed(3)}</button></div>)}<small>実績＝受入実績確定済み。差分＝取消・受入不可を除く予定−実績（便）。未着は未到着の便で、遅延判定ではありません。数量の確認済みは原票照合済みのみ。旧方式の実績は未確認伝票に含めます。</small></div>;}
export function SiteSummary({rows,onOpen}){return <div className="receiving-table-wrap" role="region" aria-label="搬出元現場別の予定・実績" tabIndex={0}><table className="receiving-table"><thead><tr><th>搬出元現場</th>{['予定','実績','未着','取消','差分','未確認伝票'].map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{[...new Set(rows.map(t=>t.siteId||t.site))].map(site=>{const list=rows.filter(t=>(t.siteId||t.site)===site);return <tr key={site}><td><button onClick={()=>onOpen(list,'現場詳細')}>{list[0].site}</button></td>{['予定','実績','未着','取消','差分','未確認伝票'].map(k=><td key={k}><button aria-label={`${list[0].site}の${k}`} onClick={()=>onOpen(list,k)}>{list.filter(filters[k]).length}便</button></td>)}</tr>;})}</tbody></table>{!rows.length&&<p>該当する予定はありません。</p>}</div>;}
export default function HomeDrilldown({selection,rows,close,m,navigate,openTrip}){
 const ref=useRef(null),[selected,setSelected]=useState('');
 useEffect(()=>{const focus=document.activeElement;ref.current.showModal();return()=>focus?.focus({preventScroll:true});},[]);
 const list=rows.filter(t=>selection.ids.includes(t.id)).filter(t=>selection.kind==='確認待ち数量'?!cancelled(t)&&t.evidence?.receiptRecord?.status==='pending':filters[selection.kind]?filters[selection.kind](t):true).filter(t=>!(selection.unit&&selection.kind==='実績')||!t.evidence||t.evidence.receiptRecord?.status==='confirmed').filter(t=>!selection.unit||(selection.kind==='実績'?(t.actualUnit||t.unit):selection.kind==='確認待ち数量'?(t.evidence?.receiptRecord?.unit==='m3'?'m³':t.evidence?.receiptRecord?.unit):t.unit)===selection.unit);
 const trip=list.find(t=>t.id===selected)||list[0];
 return <dialog className="receiving-detail-panel" ref={ref} aria-labelledby="receiving-detail-title" onCancel={close}><div className="receiving-heading"><div><small>{selection.date} · {selection.kind}</small><h2 id="receiving-detail-title">搬出元現場・運行の詳細</h2></div><button autoFocus onClick={close}>詳細を閉じる</button></div><p>一覧の日付・検索・スクロール位置を保持しています。</p><div className="evidence-trip-picker">{list.map(t=><button key={t.id} aria-pressed={trip?.id===t.id} onClick={()=>setSelected(t.id)}><b>{t.vehicle}</b><span>{t.site} · 第{t.rotation||'—'}便 · {t.reception}</span></button>)}</div>{trip?<ReceivingEvidence key={trip.id} trip={trip} session={m.session} actions={m.actions} navigate={navigate} openTrip={openTrip}/>:<p>該当する明細はありません。</p>}</dialog>;
}
