import {useRef,useState} from 'react';
import {call} from '../integration/api';
import {isConfirmedRejection} from '../integration/delivery.mjs';
import ReceiptEvidence,{evidenceTime,OriginalPhoto} from './ReceiptEvidence';
import {stayMinutes} from './receivingSummary.mjs';
export function useEvidenceActions(session,refresh){
 const lock=useRef(false),key=session?`ecodump-direct-operation:${session.userId}`:null;
 const [pending,setPending]=useState(()=>key?JSON.parse(sessionStorage.getItem(key)||'null'):null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const clear=()=>{sessionStorage.removeItem(key);setPending(null);};
 async function mutate(action,body){if(lock.current||pending||!session)return;lock.current=true;setBusy(true);let acknowledged=false;try{const op={key:crypto.randomUUID(),action,body,userId:session.userId};sessionStorage.setItem(key,JSON.stringify(op));setPending(op);await call(session.token,`/actions/${action}`,{method:'POST',body,key:op.key,signal:AbortSignal.timeout(12000)});acknowledged=true;await refresh();clear();setMessage('保存後の記録を再取得しました。');}catch(e){if(!acknowledged&&isConfirmedRejection(e.status)){clear();setMessage(e.message);await refresh().catch(()=>{});}else setMessage('保存結果が不明です。再送せず処理結果を照会してください。');}finally{lock.current=false;setBusy(false);}}
 async function lookup(){if(!pending||lock.current)return;lock.current=true;setBusy(true);try{const result=await call(session.token,`/operations/${pending.key}`);if(result.state==='applied'){await refresh();clear();setMessage('保存済みの記録を再取得しました。');}else setMessage('未処理です。通信中の処理がないことを確認するまで再送しません。');}catch(e){setMessage(e.message);}finally{lock.current=false;setBusy(false);}}
 async function upload(e,b){const f=e.target.files[0];e.target.value='';if(!f)return;if(f.size>2097152){setMessage('写真は2MB以下にしてください。');return;}const reader=new FileReader();reader.onload=()=>mutate('attachment',{bookingId:b.id,tripId:b.trip?.id,filename:f.name,mime:f.type,base64:reader.result.split(',')[1]});reader.readAsDataURL(f);}
 return {mutate,upload,disabled:busy||!!pending,status:<div role="status">{busy?'処理中…':message}{pending&&<button disabled={busy} onClick={lookup}>処理結果を照会</button>}</div>};
}
export default function ReceivingEvidence({trip:t,session,actions,navigate,openTrip}){
 const [tab,setTab]=useState('車両・位置');const b=t.evidence;
 const originalActions=actions;
 if(actions&&b?.trip)actions={...actions,mutate:(action,payload)=>originalActions.mutate(action,{...payload,tripId:b.trip.id})};
 const records=b?.gateRecords||[];const duration=stayMinutes(records);
 const departure=b?.events.find(e=>e.state==='in_transit')?.reportedAt;
 return <div className="receiving-evidence"><div className="view-switch">{['車両・位置','入退場・写真','伝票・数量'].map(label=><button key={label} aria-pressed={tab===label} className={tab===label?'active':''} onClick={()=>setTab(label)}>{label}</button>)}</div>{actions?.status}
 {tab==='車両・位置'&&<section className="receiving-card"><h3>{t.vehicle} · 第{t.rotation||'—'}便</h3><dl><dt>所属会社</dt><dd>{b?.vehicleCompany||t.partner||'未登録'}</dd><dt>運転手</dt><dd>{b?.trip?.driver||t.driver||'未配車'}</dd><dt>運行状態</dt><dd>{t.tripStatus}</dd><dt>出発時刻</dt><dd>{evidenceTime(departure)}</dd><dt>出発からの経過</dt><dd>{departure?`${Math.max(0,Math.floor((Date.now()-new Date(departure))/60000))}分（表示時点）`:'出発未報告'}</dd><dt>位置・最終更新</dt><dd>位置情報未接続 · 更新時刻なし</dd><dt>到着見込み</dt><dd>推定未提供 · 予約時刻 {t.eta}</dd></dl><p>地図上のサンプル位置は、この車両の現在位置ではありません。</p><button onClick={()=>navigate('運行管制')}>既存の運行地図を開く（サンプル）</button><button onClick={()=>openTrip(t.id)}>予約詳細・受付を開く</button></section>}
 {tab==='入退場・写真'&&<section className="receiving-card"><h3>車番 {t.vehicle} の入退場実績</h3><p>カメラ未接続 · 到着・荷下ろし報告から入退場時刻を自動確定しません。</p><p>滞在時間：{duration===null?'未確定（入退場の両方・照合状況を確認）':`${duration}分`}</p>{records.map(r=><article key={r.id} className="evidence-gate"><b>{r.plate} / {r.direction==='entry'?'入場':'退場'}</b><p>{evidenceTime(r.occurred_at)} · 人による記録 · {r.status==='confirmed'?'照合済み':r.status==='dismissed'?'重複・誤検知（除外）':'要確認'} / {r.issue}</p><p>対象予約：{r.booking_id||'未照合'}</p>{r.attachment_id&&<OriginalPhoto token={session?.token} attachment={b.attachments.find(a=>a.id===r.attachment_id)}/>}<p>確認日時：{evidenceTime(r.confirmed_at)} / {r.reason}</p>{r.status==='pending'&&session&&<form onSubmit={e=>{e.preventDefault();actions.mutate('gate_review',{recordId:r.id,bookingId:b.id,expectedVersion:r.version,reason:new FormData(e.currentTarget).get('reason')});}}><label>照合理由<input name="reason" required/></label><button disabled={actions.disabled}>車番・対象運行を照合</button></form>}</article>)}{!records.length&&<p>入退場記録はありません。</p>}{session&&b?.trip?<GateForm booking={b} actions={actions}/>:<p>保存するにはログインし、配車済みの運行を選択してください。</p>}</section>}
 {tab==='伝票・数量'&&(session&&b?<ReceiptEvidence booking={b} token={session.token} {...actions}/>:<section className="receiving-card"><h3>伝票・数量確認</h3><p>サンプル予定数量 {t.planned} {t.unit} / 実績 {t.actual||'未確認'} {t.unit}</p><p>原票は未接続です。ログイン後は原本写真・入力値・確認履歴を同じ画面で確認できます。</p></section>)}
 </div>;
}
export function GateForm({booking:b,actions,locationId}){
 return <form className="evidence-gate" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);actions.mutate('gate_record',{bookingId:b?.id,locationId:b?.location.id||locationId,plate:f.get('plate'),direction:f.get('direction'),occurredAt:new Date(`${f.get('at')}:00+09:00`).toISOString(),issue:f.get('issue'),attachmentId:f.get('photo')||null,reason:f.get('reason')});}}><h4>入退場を記録（人による確認用）</h4><div className="evidence-columns"><label>車番<input name="plate" defaultValue={b?.vehiclePlate||b?.trip?.vehicle||''} required maxLength={80}/></label><label>区分<select name="direction"><option value="entry">入場</option><option value="exit">退場</option></select></label><label>記録時刻（日本時間）<input name="at" type="datetime-local" required/></label><label>読取・照合状態<select name="issue"><option value="none">手動記録・照合待ち</option><option value="unread">未読取</option><option value="unregistered">未登録車両</option><option value="unexpected">予定外車両</option><option value="duplicate">二重検知の疑い</option></select></label></div>{b&&<label>運行に紐付く写真<select name="photo"><option value="">写真なし</option>{b.attachments.filter(a=>a.mime.startsWith('image/')).map(a=><option key={a.id} value={a.id}>{a.filename}</option>)}</select></label>}<label>記録メモ<input name="reason" maxLength={1000}/></label><button disabled={actions.disabled}>要確認として記録</button></form>;
}
