import {useEffect,useState} from 'react';
export const quantityUnit=u=>u==='m3'?'m³':u;
export const evidenceTime=t=>t?new Date(t).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'未記録';
export function OriginalPhoto({attachment,token,onViewed}){
 const [url,setUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let active=true,objectUrl;setUrl('');setError('');if(!attachment||!token)return;fetch(`/api/direct/attachments/${attachment.id}`,{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{if(!r.ok)throw Error('原票を取得できません。権限・接続を確認してください。');objectUrl=URL.createObjectURL(await r.blob());if(active)setUrl(objectUrl);}).catch(e=>active&&setError(e.message));return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[attachment?.id,token]);
 return <div className="evidence-original">{error?<p role="alert">{error}</p>:url?<><img src={url} alt={`原本写真：${attachment.filename}`} onLoad={()=>onViewed?.(attachment.id)}/><a href={url} download={attachment.filename}>原本を取得</a></>:<p>{attachment?'原本を読み込み中…':'原本写真は未提出です。'}</p>}</div>;
}
export default function ReceiptEvidence({booking:b,token,mutate,disabled=false,upload}){
 const rc=b.receiptRecord,receiver=b.canConfirm,driver=b.canReport;
 const [photoId,setPhotoId]=useState(rc?.attachment_id||''),[viewed,setViewed]=useState(''),[historyPhoto,setHistoryPhoto]=useState('');
 const planned=b.trip?.plannedQuantity??b.quantity, plannedUnit=b.trip?.unit||b.unit;
 const photos=b.attachments.filter(a=>a.mime.startsWith('image/'));
 const original=photos.find(a=>a.id===(historyPhoto||rc?.attachment_id||photoId));
 const submit=(action,e)=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate(action,{bookingId:b.id,expectedVersion:rc?.version||0,attachmentId:photoId,quantity:Number(f.get('quantity')),unit:f.get('unit'),reason:f.get('reason')||'',originalChecked:f.get('checked')==='on'});};
 return <section className="receiving-card receipt-evidence"><h3>伝票・数量確認</h3><p>原本写真と入力値を照合してください。OCRは未接続です。</p><div className="receipt-totals"><span>便の予定<b>{planned} {quantityUnit(plannedUnit)}</b></span><span>原票の報告<b>{rc?`${rc.quantity} ${quantityUnit(rc.unit)}`:"未提出"}</b></span><span>原票照合済み数量<b>{rc?.status==="confirmed"&&b.actual?`${b.actual.quantity} ${quantityUnit(b.actual.unit)}`:"未確定"}</b></span></div>{rc&&<p>{rc.unit===plannedUnit?`予定との差：${Number((rc.quantity-planned).toFixed(3))} ${quantityUnit(rc.unit)}`:"予定と原票の単位が異なるため、差分を計算しません。"}</p>}<div className="evidence-columns"><div>{historyPhoto&&<button onClick={()=>setHistoryPhoto('')}>現在の原票に戻る</button>}<OriginalPhoto attachment={original} token={token} onViewed={setViewed}/></div><div>
 {b.driverDocumentFields&&<dl>{Object.entries({date:'伝票日付',number:'伝票番号',missingNumberReason:'番号なし理由',item:'品名・土質',plate:'原票車番',origin:'搬出元',destination:'受入先',gross:'総重量',tare:'空車重量',net:'正味重量'}).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{b.driverDocumentFields[key]||'記載なし'}</dd></div>)}</dl>}{rc&&<><p><b>{({pending:'確認待ち',returned:'差戻し',confirmed:'確認済み'})[rc.status]}</b> · {rc.quantity} {quantityUnit(rc.unit)}</p><p>{rc.source==='driver'?'担当ドライバー提出':'受入担当による転記'} · {evidenceTime(rc.submitted_at)}</p>{rc.reason&&<p>理由：{rc.reason}</p>}{rc.confirmed_at&&<p>確認者：{rc.confirmedName||rc.confirmed_by} · {evidenceTime(rc.confirmed_at)}</p>}</>}
 {(!rc||rc.status==='returned')&&!b.actual&&(receiver||driver)&&<form onSubmit={e=>submit('receipt_submit',e)}><h4>{rc?'原票を再提出':'原票の入力値を提出'}</h4>{upload&&<label>原票写真を追加<input type="file" accept="image/png,image/jpeg" disabled={disabled} onChange={e=>upload(e,b)}/></label>}<label>原票写真<select required value={photoId} onChange={e=>setPhotoId(e.target.value)}><option value="">選択してください</option>{photos.map(a=><option key={a.id} value={a.id}>{a.filename}</option>)}</select></label><QuantityInputs quantity={rc?.quantity} unit={rc?.unit||b.unit}/><label>提出・再提出理由<textarea name="reason" required={!!rc} maxLength={1000}/></label><button disabled={disabled||!photoId}>確認待ちとして提出</button></form>}
 {receiver&&rc&&['pending','confirmed'].includes(rc.status)&&<form key={rc.version} onSubmit={e=>submit(rc.status==='confirmed'?'receipt_correct':'receipt_confirm',e)}><h4>{rc.status==='confirmed'?'確認済み数量を訂正':'原票を確認して実績確定'}</h4><QuantityInputs quantity={rc.quantity} unit={rc.unit}/><label>差異・訂正理由<textarea name="reason" required={rc.status==='confirmed'} maxLength={1000}/></label><label className="evidence-check"><input name="checked" type="checkbox" required disabled={!!historyPhoto||viewed!==rc.attachment_id}/>原本写真と数量・単位を照合しました</label><button className="primary" disabled={disabled||!!historyPhoto||viewed!==rc.attachment_id||b.trip?.status!=='unloaded'}>{rc.status==='confirmed'?'理由付きで訂正を保存':'照合して実績を確定'}</button>{b.trip?.status!=='unloaded'&&<p>荷下ろし完了報告後に確定できます。</p>}</form>}
 {receiver&&rc?.status==='pending'&&<form onSubmit={e=>submit('receipt_return',e)}><label>差戻し理由<textarea name="reason" required maxLength={1000}/></label><button disabled={disabled}>理由付きで差し戻す</button></form>}
 {!rc&&b.actual&&<p>旧方式の実績：{b.actual.quantity} {quantityUnit(b.actual.unit)}。原票照合履歴はありません。原票照合済み数量には含めません。</p>}
 </div></div><details><summary>提出・確認・訂正の履歴（{b.receiptHistory?.length||0}件）</summary>{b.receiptHistory?.map(h=><p key={h.id}>{evidenceTime(h.recorded_at)} · {h.actorName} · {h.action}<br/>{h.before_data?`${h.before_data.quantity} ${quantityUnit(h.before_data.unit)} / ${h.before_data.status}`:'未提出'} → {h.after_data.quantity} {quantityUnit(h.after_data.unit)} / {h.after_data.status}<br/>理由：{h.reason||'初回提出・変更なし'}<button onClick={()=>setHistoryPhoto(h.after_data.attachment_id)}>この版の原本を表示</button></p>)}</details></section>;
}
function QuantityInputs({quantity='',unit='m3'}){return <div className="evidence-columns"><label>原票の数量<input type="number" name="quantity" min="0.001" max="999999999" step="0.001" defaultValue={quantity} required/></label><label>原票の単位<select name="unit" defaultValue={unit}><option value="m3">m³</option><option value="t">t</option></select></label></div>;}
