import {useEffect,useState} from 'react';
import {call} from '../integration/api';
import {evidenceTime} from './ReceiptEvidence';
const issueLabel={delay:'遅延',not_arrived:'未着',refused:'受入不可',vehicle_trouble:'車両故障',receiving_unavailable:'受入先事情',assignment_mismatch:'配車の不一致',other:'その他'};
export default function ReceivingExceptions({booking:b,actions,token}){
 const [history,setHistory]=useState([]),[error,setError]=useState('');
 useEffect(()=>{let active=true;call(token,`/bookings/${b.id}/history`).then(r=>{if(active){setHistory(r.history);setError('');}}).catch(e=>active&&setError(e.message));return()=>{active=false;};},[token,b.id,b.version,b.trip?.version]);
 return <section className="rc-tabs">
 {['requested','change_requested'].includes(b.status)&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);actions.mutate('booking_reply',{bookingId:b.id,expectedVersion:b.version,decision:f.get('decision'),reason:f.get('reason')});}}><h3>予約への返答</h3><label>返答<select name="decision"><option value="change_requested">変更を依頼</option><option value="rejected">受入不可</option></select></label><label>条件不一致・変更依頼の理由<textarea name="reason" required maxLength={2000}/></label><button disabled={actions.disabled}>理由付きで返答を保存</button></form>}
 {b.trip&&!['unloaded','cancelled','refused'].includes(b.trip.status)&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);actions.mutate('trip_issue',{bookingId:b.id,tripId:b.trip.id,expectedVersion:b.trip.version,kind:f.get('kind'),reason:f.get('reason')});}}><h3>当日の遅延・未着・受入不可</h3><label>区分<select name="kind"><option value="delay">遅延</option><option value="not_arrived">未着</option><option value="refused">受入不可（この便の受入を停止）</option></select></label><label>理由・対応内容<textarea name="reason" required maxLength={2000}/></label><button disabled={actions.disabled}>対応記録を保存</button></form>}
 {(b.issues||[]).map(i=><article key={i.id}><h4>{issueLabel[i.kind]||i.kind} · {i.status==='open'?'対応中':'対応済み'}</h4><p>{i.actorName||"担当者記録あり"} / {i.reason} / {evidenceTime(i.createdAt||i.created_at)}</p>{i.status==='open'&&<form onSubmit={e=>{e.preventDefault();actions.mutate('issue_resolve',{bookingId:b.id,tripId:b.trip.id,expectedVersion:b.trip.version,issueId:i.id,reason:new FormData(e.currentTarget).get('reason')});}}><label>対応結果<textarea name="reason" required maxLength={2000}/></label><button disabled={actions.disabled}>対応結果を記録</button></form>}{i.resolution&&<p>{i.resolution}</p>}</article>)}
 <details><summary>予約・運行の変更履歴（{history.length}件）</summary>{error&&<p role="alert">履歴を取得できません：{error}</p>}{history.map((h,n)=><article key={h.operation_key||n}><b>{h.action}</b><p>{evidenceTime(h.created_at)} / {h.actorName||h.actor_name||h.actor_id||'担当者はAPI確認中'}</p><p>{h.after_data?.reason||'理由の記載なし'}</p><details><summary>変更前後を確認</summary><HistoryChange before={h.before_data} after={h.after_data}/></details></article>)}</details>
 </section>;
}

function HistoryChange({before,after}){const a=before?.booking||before||{},b=after?.booking||after||{};const fields=[['status','予約状態'],['planned_at','搬入予定'],['soil','土質'],['quantity','予約数量'],['unit','単位']];return <div className="rc-table"><table><thead><tr><th>項目</th><th>変更前</th><th>変更後</th></tr></thead><tbody>{fields.filter(([k])=>a[k]!==undefined||b[k]!==undefined).map(([k,label])=><tr key={k}><th>{label}</th><td>{String(a[k]??'—')}</td><td>{String(b[k]??'—')}</td></tr>)}</tbody></table></div>;}
