import ReceivingExceptions from './ReceivingExceptions';
import {resultGroups} from './resultGroups.mjs';
import {useEffect,useState,useRef,useLayoutEffect} from 'react';
import {call,names} from '../integration/api';
import {useEvidenceActions,GateForm} from './ReceivingEvidence';
import ReceiptEvidence,{evidenceTime} from './ReceiptEvidence';
import {bookingLabels} from './liveModel.mjs';
import './connected-receiving.css';
const day=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});
const unit=u=>u==='m3'?'m³':u;
const key=b=>b.trip?.id||b.id;
const state=b=>({cancelled:'取消',refused:'受入不可'})[b.trip?.status]||bookingLabels[b.status]||b.status;
export default function ReceivingConnected({session,view='home',bookingId}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(bookingId||''),[date,setDate]=useState(()=>new URLSearchParams(location.search).get('date')||day()),[search,setSearch]=useState(''),[period,setPeriod]=useState('day'),[group,setGroup]=useState('site'),[reservation,setReservation]=useState('');
 async function load(){setLoading(true);try{const r=await call(session.token,'/bookings');setRows(r.bookings.filter(b=>b.canConfirm));setError('');}catch(e){setError(e.message);throw e;}finally{setLoading(false);}}
 useEffect(()=>{load().catch(()=>{});},[session.token]);
 useEffect(()=>setSelected(bookingId||''),[bookingId]);
 const actions=useEvidenceActions(session,load);
 const root=useRef(null),scroll=useRef([]);
 function openDetails(id){scroll.current=[];for(let n=root.current;n;n=n.parentElement)if(n.scrollHeight>n.clientHeight)scroll.current.push([n,n.scrollTop]);setSelected(id);}
 useLayoutEffect(()=>{if(!selected)for(const [node,top] of scroll.current)node.scrollTop=top;},[selected]);
 const filtered=rows.filter(b=>(period==='month'?b.date?.slice(0,7)===date.slice(0,7):b.date===date)&&[b.site.name,b.location.name,b.trip?.vehicle,b.trip?.driver,b.soil,b.constructionCompany].join(' ').includes(search));
 const list=filtered.filter(b=>!reservation||b.id===reservation);
 const reservations=[...new Map(filtered.map(b=>[b.id,b])).values()];
 const b=rows.find(b=>key(b)===selected)||rows.find(b=>b.id===selected);
 const tripActions=b?{...actions,mutate:(action,payload)=>actions.mutate(action,{...payload,tripId:b.trip?.id}),upload:(e)=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.size>2097152){setError('写真は2MB以下にしてください。');return;}const reader=new FileReader();reader.onload=()=>actions.mutate('attachment',{bookingId:b.id,tripId:b.trip?.id,filename:f.name,mime:f.type,base64:reader.result.split(',')[1]});reader.readAsDataURL(f);}}:actions;
 return <section className="rc-live" ref={root}><div className="receiving-heading"><div><h2>{view==='results'?'受入実績・数量集計':'搬入予約・受付'}</h2><p>共通DB · 許可された受入場所のみ表示 · 検証用</p></div><button onClick={()=>load().catch(()=>{})} disabled={loading||actions.disabled}>{loading?'取得中…':'再取得'}</button></div>{error&&<p role="alert">{error}</p>}{actions.status}
 {b?<><button onClick={()=>setSelected('')}>← 一覧に戻る</button><h3>{b.site.name} → {b.location.name}</h3><p>予約 {b.id} / 便 {b.trip?.rotation||'未配車'}</p><div className="rc-state"><span>予約：{state(b)}</span><span>運行：{names[b.trip?.status]||b.trip?.status||'未配車'}</span><span>入場：{b.gateRecords?.some(g=>g.direction==='entry'&&g.status==='confirmed')?'確認済み':'未確認'}</span><span>数量：{b.receiptRecord?.status==='confirmed'?'確定済み':b.receiptRecord?.status==='returned'?'差戻し中':b.actual?'旧実績あり・原票未照合':'未確定'}</span></div><dl className="rc-info"><dt>施工会社</dt><dd>{b.constructionCompany||b.construction?.name||'共通API未提供'}</dd><dt>日時 / 土質</dt><dd>{evidenceTime(b.trip?.plannedAt||b.plannedAt)} / {b.soil}</dd><dt>車番 / 運転手</dt><dd>{b.vehiclePlate||b.trip?.vehicle||'未配車'} / {b.trip?.driver||'未配車'}</dd><dt>予約数量 / 便予定</dt><dd>{b.quantity} {unit(b.unit)} / {b.trip?.plannedQuantity??b.quantity} {unit(b.trip?.unit||b.unit)}</dd><dt>原票数量 / 確定数量</dt><dd>{b.receiptRecord?`${b.receiptRecord.quantity} ${unit(b.receiptRecord.unit)}`:'未提出'} / {b.actual?`${b.actual.quantity} ${unit(b.actual.unit)}${b.receiptRecord?.status==='confirmed'?'':'（旧実績・原票未照合）'}`:'未確定'}</dd>{b.matchAgreementId&&<><dt>発生土マッチ合意ID</dt><dd>{b.matchAgreementId}</dd></>}<dt>条件</dt><dd>{b.agreementNote||'未登録'}</dd></dl>
 {['requested','change_requested'].includes(b.status)&&<button disabled={actions.disabled} onClick={()=>actions.mutate('confirm',{bookingId:b.id,expectedVersion:b.version,agree:true})}>内容を確認して受入承認</button>}
 <ReceivingExceptions booking={b} actions={tripActions} token={session.token}/><p>到着報告・入場確認・荷下ろし・数量確定はそれぞれ別に管理します。GPS・ゲート機器・QR・OCRは未接続です。</p>
 <div className="rc-tabs"><details open><summary>到着報告・入退場</summary>{(b.events||[]).map(e=><p key={e.id}>{names[e.state]||e.state}：{evidenceTime(e.reportedAt)}</p>)}{(b.gateRecords||[]).map(g=><article key={g.id}><p>{g.direction==='entry'?'入場':'退場'}：{evidenceTime(g.occurred_at)} / {g.plate} / {g.status} / 確認者 {g.confirmed_by||'未確認'}</p>{g.status==='pending'&&<form onSubmit={e=>{e.preventDefault();tripActions.mutate('gate_review',{bookingId:b.id,recordId:g.id,expectedVersion:g.version,reason:new FormData(e.currentTarget).get('reason')});}}><input name="reason" aria-label="照合理由" required placeholder="車番・予約・便の照合理由"/><button disabled={actions.disabled}>手動照合を確定</button></form>}</article>)}{b.trip&&!['cancelled','refused'].includes(b.trip.status)&&<GateForm booking={b} actions={tripActions}/>}</details><details open><summary>原票・数量確認</summary>{b.trip?<ReceiptEvidence key={key(b)} booking={b} token={session.token} {...tripActions}/>:<p>配車・原票提出後に確認できます。</p>}</details></div></>:<><div className="rc-filters"><label>表示日<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{view==='results'&&<><label>期間<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="day">日別</option><option value="month">月別</option></select></label><label>集計<select value={group} onChange={e=>setGroup(e.target.value)}><option value="site">現場・工区別</option><option value="company">施工会社別</option><option value="soil">土質別</option></select></label></>}<label>予約単位で表示<select value={reservation} onChange={e=>setReservation(e.target.value)}><option value="">すべての予約・便</option>{reservations.map(r=><option key={r.id} value={r.id}>{r.site.name} · {r.id.slice(0,8)} · {filtered.filter(b=>b.id===r.id&&b.trip).length}便</option>)}</select></label><label>検索<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="現場・場所・車両・運転手"/></label></div>{view==='results'&&<><p>確認済み数量は原票照合済みのみ。旧実績・未確認・差戻し中の数量は含めず、tとm³を別集計します。便数・実車両台数は表示中の集計区分ごとです。</p><Results rows={list} group={group}/></>}
 <div className="rc-table"><table><thead><tr><th>予定日時 / 予約</th><th>現場 → 受入先</th><th>便・車両</th><th>予定 / 原票 / 確定</th><th>予約・運行</th><th>操作</th></tr></thead><tbody>{list.map(r=><tr key={key(r)}><td>{evidenceTime(r.trip?.plannedAt||r.plannedAt)}<small>{r.id.slice(0,8)}</small></td><td>{r.site.name}<small>{r.location.name}</small></td><td>第{r.trip?.rotation||'—'}便<small>{r.vehiclePlate||r.trip?.vehicle||'未配車'}</small></td><td>{r.trip?.plannedQuantity??r.quantity} {unit(r.trip?.unit||r.unit)} / {r.receiptRecord?`${r.receiptRecord.quantity} ${unit(r.receiptRecord.unit)}`:'—'} / {r.actual?`${r.actual.quantity} ${unit(r.actual.unit)}${r.receiptRecord?.status==='confirmed'?'':'（旧実績・未照合）'}`:'—'}</td><td>{state(r)}<small>{names[r.trip?.status]||r.trip?.status||'未配車'}</small></td><td><button onClick={()=>openDetails(key(r))}>詳細</button></td></tr>)}</tbody></table></div>{!list.length&&!loading&&!error&&<p>指定条件の予約・便はありません。</p>}</>}
 </section>;
}
function Results({rows,group}){
 const groups=resultGroups(rows,group);
 return <div className="rc-table"><table><thead><tr><th>集計区分</th><th>便数 / 実車両台数</th><th>未提出 / 差戻し / 未確認</th><th>確認済み数量</th></tr></thead><tbody>{groups.map(g=><tr key={g.name+g.unit}><td>{g.name} / {unit(g.unit)}</td><td>{g.trips.size}便 / {g.vehicles.size}台</td><td>{g.missing} / {g.returned} / {g.pending}</td><td>{g.confirmed.toFixed(3)} {unit(g.unit)}</td></tr>)}</tbody></table></div>;
}
