-- Direct transport workflow. Apply only after review in a linked Supabase project.
create type public.business_role as enum ('construction', 'receiving', 'driver');
create type public.reservation_status as enum ('requested', 'confirmed', 'cancelled', 'rejected');
create type public.trip_status as enum ('assigned', 'arrived', 'departed', 'unloaded');
create type public.trip_event_type as enum ('arrived', 'departed', 'unloaded', 'delayed');
create type public.receipt_status as enum ('confirmed', 'corrected');
alter table public.memberships add column if not exists business_role public.business_role;
create table public.organization_relationships (source_organization_id uuid not null references public.organizations(id), partner_organization_id uuid not null references public.organizations(id), relationship_type text not null check(relationship_type in ('direct_transport','carrier')), active boolean not null default true, primary key(source_organization_id, partner_organization_id, relationship_type));
create table public.receiving_locations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, address text not null, active boolean not null default true, created_at timestamptz not null default now());
create table public.reservations (id uuid primary key default gen_random_uuid(), source_organization_id uuid not null references public.organizations(id), receiving_organization_id uuid not null references public.organizations(id), site_id uuid not null references public.sites(id), receiving_location_id uuid not null references public.receiving_locations(id), status public.reservation_status not null default 'requested', planned_at timestamptz not null, soil_type text not null, planned_quantity numeric(10,2) not null check(planned_quantity>0), unit text not null, version bigint not null default 1, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.trips (id uuid primary key default gen_random_uuid(), reservation_id uuid not null references public.reservations(id), rotation_no integer not null check(rotation_no>0), vehicle_id uuid references public.vehicles(id), driver_id uuid references public.drivers(id), status public.trip_status not null default 'assigned', version bigint not null default 1, assigned_at timestamptz not null default now(), completed_at timestamptz, unique(reservation_id, rotation_no));
create table public.trip_state_reports (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips(id), event_type public.trip_event_type not null, actor_user_id uuid not null references public.profiles(id), operation_key uuid not null unique, occurred_at timestamptz not null default now(), payload jsonb not null default '{}'::jsonb);
create table public.receiving_results (id uuid primary key default gen_random_uuid(), trip_id uuid not null unique references public.trips(id), actual_quantity numeric(10,2) not null check(actual_quantity>0), unit text not null, status public.receipt_status not null default 'confirmed', version bigint not null default 1, confirmed_by uuid not null references public.profiles(id), confirmed_at timestamptz not null default now());
create table public.receiving_result_corrections (id uuid primary key default gen_random_uuid(), receiving_result_id uuid not null references public.receiving_results(id), previous_quantity numeric(10,2) not null, corrected_quantity numeric(10,2) not null check(corrected_quantity>0), reason text not null check(length(trim(reason))>0), corrected_by uuid not null references public.profiles(id), corrected_at timestamptz not null default now());
create table public.workflow_operations (operation_key uuid primary key, actor_user_id uuid not null references public.profiles(id), status text not null check(status in ('processing','completed','failed')), response_status integer, response_body jsonb, created_at timestamptz not null default now());
create table public.workflow_attachments (id uuid primary key default gen_random_uuid(), reservation_id uuid references public.reservations(id), trip_id uuid references public.trips(id), owner_organization_id uuid not null references public.organizations(id), storage_key text not null unique, file_name text not null, created_at timestamptz not null default now());
alter table public.organization_relationships enable row level security; alter table public.receiving_locations enable row level security; alter table public.reservations enable row level security; alter table public.trips enable row level security; alter table public.trip_state_reports enable row level security; alter table public.receiving_results enable row level security; alter table public.receiving_result_corrections enable row level security; alter table public.workflow_operations enable row level security; alter table public.workflow_attachments enable row level security;
revoke all on public.organization_relationships, public.receiving_locations, public.reservations, public.trips, public.trip_state_reports, public.receiving_results, public.receiving_result_corrections, public.workflow_operations, public.workflow_attachments from anon, authenticated;
grant select on public.receiving_locations, public.reservations, public.trips, public.trip_state_reports, public.receiving_results, public.receiving_result_corrections to authenticated;
create policy relationship_party_read on public.organization_relationships for select to authenticated using (private.has_org_access(source_organization_id) or private.has_org_access(partner_organization_id));
create policy receiving_location_participant_read on public.receiving_locations for select to authenticated using (private.has_org_access(organization_id));
create policy reservation_participant_read on public.reservations for select to authenticated using (private.has_org_access(source_organization_id) or private.has_org_access(receiving_organization_id));
create policy trip_participant_read on public.trips for select to authenticated using (exists (select 1 from public.reservations r where r.id=reservation_id and (private.has_org_access(r.source_organization_id) or private.has_org_access(r.receiving_organization_id))) or exists (select 1 from public.drivers d where d.id=driver_id and d.profile_id=(select auth.uid())));
create policy report_participant_read on public.trip_state_reports for select to authenticated using (exists (select 1 from public.trips t join public.reservations r on r.id=t.reservation_id where t.id=trip_id and (private.has_org_access(r.source_organization_id) or private.has_org_access(r.receiving_organization_id) or exists(select 1 from public.drivers d where d.id=t.driver_id and d.profile_id=(select auth.uid())))));
create policy result_participant_read on public.receiving_results for select to authenticated using (exists (select 1 from public.trips t join public.reservations r on r.id=t.reservation_id where t.id=trip_id and (private.has_org_access(r.source_organization_id) or private.has_org_access(r.receiving_organization_id))));
create policy result_correction_participant_read on public.receiving_result_corrections for select to authenticated using (exists (select 1 from public.receiving_results rr join public.trips t on t.id=rr.trip_id join public.reservations r on r.id=t.reservation_id where rr.id=receiving_result_id and (private.has_org_access(r.source_organization_id) or private.has_org_access(r.receiving_organization_id))));
-- Direct browser writes stay denied. Security-definer RPC/Edge API must validate role,
-- scope, state, expected version, and idempotency key before every mutation.
